### ISSUE TITLE
Can someone write a method that computes the real time "number of facts" in PLDB?

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#105]
For now let's define it as 'non blank cells in pldb.csv'. Let's include the computeds.

I would think a fantastic v1 would be for someone to just find the exact number and put it in the readme.md. No code needed for v1.

**Comment by SRS-WRKS** [comment]
I have 135239 as an answer

**Comment by breck7** [comment]
Your number sounds more accurate than mine @SRS-WRKS .

"PLDB builds one main CSV file. languages.csv contains over 42k facts across 4110 rows and 307 columns and is 3.6MB uncompressed. Every row is a language and every language is one row."

https://github.com/breck7/pldb/commit/6b568122f37513e33d6b7c939c7d8edac2016249

**Comment by SRS-WRKS** [comment]
@breck7  Here is the shell script one liner, if you want to verify or add to archive
`tail -n +2  site/pldb.csv | sed 's/,,,*/,/g' | awk -F, '{for (i =1; i<=NF ; i++) { print $i; printf "\n" }  }' | sed '/^$/d'  | wc -l`

**Comment by breck7** [comment]
Thanks @SRS-WRKS ! Love your approach.

I actually realized I had a way to do it with grammar. The poorly named `getTopDownArray()` method in `jtree` returns a TreeNode for every line in a tree doc, which equates to at least one fact (example code would span multiple lines so I filter those).

Of course, some of the lines contain many facts, so this is still a good undercount, but better than before.

https://github.com/breck7/pldb/commit/35a06149d1e1cf4edca67b3c1757da1bd6dab718
