### ISSUE TITLE
Add a fun fact about how Javascript was named and why it is related to Java (even if not like, as related as you would think)

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#106]

**Comment by LikhithShankarPrithvi** [comment]
Fun Fact - Although Javascript and its interpreter implementation were called LiveScript, at the time, the dot-com boom had begun and Java was the hot new language, so Netscape management considered the JavaScript name which is a marketing ploy.

#106

**Comment by breck7** [comment]
Thanks @LikhithShankarPrithvi ! Do you have a link to your source?

**Comment by LikhithShankarPrithvi** [comment]
[Speech by Eich, developer of JS](https://www.youtube.com/watch?v=XOmhtfTrRxc&t=2m5s) - story behind Naming javascript
[Early name LiveScript](https://web.archive.org/web/20080208124612/https://wp.netscape.com/comprod/columns/techvision/innovators_be.html) - by Eich as well.

**Comment by breck7** [comment]
Nice! Do you think you could try adding a fact @LikhithShankarPrithvi ? (https://build.pldb.com/edit/javascript)

**Comment by LikhithShankarPrithvi** [comment]
Hey @breck7 I have added the JS - funfact in the code and created a pull request. Please check it out.

**Comment by breck7** [comment]
Great job @LikhithShankarPrithvi !
