### ISSUE TITLE
How to add mulitple references for a database things entry 

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#107]
File database/things/bbx.pldb
 Needs two references https://www.basis.com/bbj and https://trademark.trademarkia.com/bbx-78639049.html

I cant seem to figure out how to do it.

**Comment by breck7** [comment]
Great question! A file can have unlimited `reference` keywords.

`reference URLONE
reference URLTWO
...`

**Comment by SRS-WRKS** [comment]
Local tests here fail with :
`[
  ExtraWordError {
    _node: referenceNode {
      _nodeCreationTime: 341562.576166,
      _parent: [pldbNode],
      _line: 'reference  https://www.basis.com/bbj ',
      _children: [],
      _cachedLineNumber: 8,
      _words: [Array]
    },
    _cell: GrammarExtraWordCellTypeCell {
      _typeDef: undefined,
      _node: [referenceNode],
      _isCatchAll: true,
      _index: 2,
      _cellTypeId: 'extraWordCell',
      _nodeTypeDefinition: [nodeTypeDefinitionNode]
    }
  },
  ExtraWordError {
    _node: referenceNode {
      _nodeCreationTime: 341562.576166,
      _parent: [pldbNode],
      _line: 'reference  https://www.basis.com/bbj ',
      _children: [],
      _cachedLineNumber: 8,
      _words: [Array]
    },
    _cell: GrammarExtraWordCellTypeCell {
      _typeDef: undefined,
      _node: [referenceNode],
      _isCatchAll: true,
      _index: 3,
      _cellTypeId: 'extraWordCell',
      _nodeTypeDefinition: [nodeTypeDefinitionNode]
    }
  }
]


`

When two reference fields:
 `reference  https://www.basis.com/bbj
reference https://trademark.trademarkia.com/bbx-78639049.html
`

Are present in file 
`database/things/bbx.pldb`

**Comment by breck7** [comment]
You have an extra space after `bbj`. Hence the extra word error. Sorry that is very confusing. Let me see if I can make a better error message for that kind of situation.
