### ISSUE TITLE
Make sure every language has an `appeared` year

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#110]
looks like we're at 92%. this should be 100%

<img width="647" alt="Screen Shot 2022-09-20 at 8 15 05 AM" src="https://user-images.githubusercontent.com/74692/191333524-047dee36-fa1a-4f16-80cf-26ef628e1ecb.png">

**Comment by AlexUrielContreras** [comment]
Hey, I'm new to open source and would like to contribute to this repo from this issue!

**Comment by breck7** [comment]
Go for it @AlexUrielContreras ! Let us know if you have any problems.

**Comment by mahadwaseem123** [comment]
Hi @breck7 , I will work to make it 100%.

**Comment by breck7** [comment]
Awesome @mahadwaseem123 !

**Comment by mahadwaseem123** [comment]
Hi @breck7 , increased the coverage by 1%. Almost added appeared year in 50 entities. Almost 250-300 remaining. Working on it to increase coverage more.

**Comment by mahadwaseem123** [comment]
Hi @breck7 , we are now on 95%. 
<img width="869" alt="Screenshot 2022-10-05 at 3 55 03 PM" src="https://user-images.githubusercontent.com/36690888/194044878-013d4c76-6ea9-459a-8f9b-51288515cf36.png">

**Comment by celtic-coder** [comment]
Good work, @mahadwaseem123!

**Comment by mahadwaseem123** [comment]
Hi @breck7 , updated PR for this issue is #191 . Kindly check

**Comment by breck7** [comment]
Great work @mahadwaseem123 !

**Comment by breck7** [comment]
Only 104 left to go:

https://build.pldb.com/search?q=select+type+reference+website%0D%0Amissing+appeared

**Comment by stavares843** [comment]
quick question 🔨 do we have any database where we can grab the year and add the ''appeared'' or do we need to google it manually?

**Comment by breck7** [comment]
@stavares843 most of the `appeared` came from databases such as Wikipedia and Github. But probably 1,000 of them were manual. I'm guessing 50% of the ones remaining need to be done manually, and 50% could be done by fixing scripts or adding new sources in `code/crawlers`

**Comment by stavares843** [comment]
thanks! 🔨

**Comment by stavares843** [comment]
🎉

**Comment by breck7** [comment]
I am going to do all the ones letters B - K now.

**Comment by stavares843** [comment]
neat, im doing the ones in the bottom from R to X

**Comment by stavares843** [comment]
@breck7 do you want me to merge all the above or do you prefer to merge? i can merge if you want as well

**Comment by breck7** [comment]
Okay I'm going to do A - M

**Comment by stavares843** [comment]
Searched 4,775 files and found 29 matches in 0.02s. 🎉 

will do the the N - R 🔨

**Comment by breck7** [comment]
Searched 4,774 files and found 10 matches in 0.03s.

You got this @stavares843 !

**Comment by stavares843** [comment]
regarding Procfile, i couldn't find a specific date

also asked ChatGTP and he replied with the following

<img width="838" alt="Captura de ecrã 2023-02-08, às 17 24 17" src="https://user-images.githubusercontent.com/29093946/217605528-21947cc5-5a8f-4261-9c14-6c45bc786228.png">

**Comment by stavares843** [comment]
missing info on

<br class="Apple-interchange-newline">[prolog-pack-pm](https://pldb.com/languages/prolog-pack-pm.html)
<br class="Apple-interchange-newline">[pypi-pm](https://pldb.com/languages/pypi-pm.html)
<br class="Apple-interchange-newline">[python-format-spec](https://pldb.com/languages/python-format-spec.html)

**Comment by stavares843** [comment]
the rest is done, still trying to find a specific date in those, so far couldn't find in google, also asked ChatGTP and he says the release date is unclear

still searching

**Comment by breck7** [comment]
Okay I found a 2012 reference for procfile (https://stackoverflow.com/questions/9802259/why-do-people-use-heroku-when-aws-is-present-what-distinguishes-heroku-from-aws/9803182#9803182). It could be a year or two earlier but that at least gets us close.

**Comment by stavares843** [comment]
neat, i didn't want to add wrong info 😂 will update 🔨

**Comment by stavares843** [comment]
still couldn't find a specific date for the other 3 above 😂

**Comment by celtic-coder** [comment]
Well done, Sara and Breck - good work! 👍
