### ISSUE TITLE
Suggestion for H1 and Title tags

### ISSUE THREAD

**Issue by celtic-coder** [breck7/pldb#111]
Hi Breck (@breck7),

The home page of the PLDB site lacks some details that are actually spelled out very carefully elsewhere on the site.

For example, the abbreviation PLDB itself. You and I know what it means, but to the uninformed observer, especially someone coming to the main PLDB page, they might well ask: _"What does PLDB mean?"_

A glance down the page would show that it might be about programming languages, but it is not very evident from first looking at the page.

The **About** page does a better job of explaining the meaning and purpose of PLDB, but some of these details should be front-and-center on the main page. 

For the search engines, these key details could be put in the H1 and Title tags and would give search users a clearer understanding of what the site is about.  Also, for the best SEO impact, both the Title and H1 tag should be the same. 

The current title tag for the main PLDB page is:

![pldb-title-tag](https://user-images.githubusercontent.com/11787866/191805346-c760205b-6fc4-4005-a771-4ea1a892f71e.png)

This is, to say the least, ahmm..... riveting! 😄 

The **Title** tag is what appears on the browser tab and is (usually) what first appears in the search engine results. **PLDB**, by itself, is not very informative.

The H1 tag is used by the search engines to categorize the content on the page. The recommendation is that there is only one H1 tag on a page and that it should give a concise summary of the page content.

The current H1 tag does not contain any text at all and is used only for linking:

![h1-tag-no-text](https://user-images.githubusercontent.com/11787866/191813970-e7f38186-2ad1-4bf7-996d-b48d08d8a931.png)

I would consider this to be a missed opportunity.

Since it is recommended that the Title tag be 65 characters or fewer, my suggestion for the Title / H1 tags would be:

**PLDB - A Comprehensive Database of Programming Languages and Features**

Ok, it is 69 characters long, and the last few characters might be chopped off in the search results, but this might be something to consider.

I see that you already have a PLDB "Header" just before the first search form:

![pldb-header](https://user-images.githubusercontent.com/11787866/191816413-8f420bd8-ff51-497f-bb7a-640cc62d8a47.png)

It may be difficult to incorporate these  H1 / Title tags changes, given the current design of the page, but I believe that it would be an important part of  giving out a clear message of what the PLDB is all about.

Again, this is just a suggestion. Feel free to ignore if it is too much work!

Kind Regards,
Liam

**Comment by breck7** [comment]
Great idea! I can take a look at a pull request, or I can get to this a little later today. Thanks so much @celtic-coder ! Little things like this make the site 1-3% better everyday and that compounds to a *much* better experience for our visitors in the long run.

**Comment by mahadwaseem123** [comment]
Hi @breck7 , what is we split this issue into parts and at least try implementing wherever possible? May be we can achieve something which can eventually improve the website's SEO. What you think?

**Comment by breck7** [comment]
For sure @mahadwaseem123! You can always post as many pull requests as possible :)
