### ISSUE TITLE
Feature request list stats at bottom of page (enhacement)

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#117]
Right now Going to the bottom of list page (for example) https://pldb.com/lists/originCommunities.html gives number of entries in the list 

Would it be possible to have a link to https://pldb.com/docs/csv.html#originCommunity so that monitoring daily additions can include bigger picture of percentage of entry covered so far/remaining ?

**Comment by breck7** [comment]
Yes! But not exactly sure what you mean. Could you attach a mockup/screenshot or send a PR?

**Comment by SRS-WRKS** [comment]
I would need to upskill to send a PR on this issue. 
As of now all i can do is attach a screenshot .  May be in the future.  Please find a mockup collage below[
![1](https://user-images.githubusercontent.com/112767375/192131539-dc516615-832c-48c1-9e24-1bdaa32e0e16.png)
](url)

**Comment by mahadwaseem123** [comment]
Hi @breck7 and @SRS-WRKS , I have tried this enhancement and I am very hopeful to push it by Monday.

**Comment by breck7** [comment]
Not yet @mahadwaseem123 ! But I am excited to. I have to think about it. Will get to it in a little bit after breakfast.

**Comment by mahadwaseem123** [comment]
Ok sure @breck7 , let me know if you like it or also if you want any change.

**Comment by mahadwaseem123** [comment]
Hi @breck7 , this is now covered in another PR. #173

**Comment by mahadwaseem123** [comment]
Hi @breck7 , this feature now points to PR #193. Kindly check and let me know if you like the enhancement.

**Comment by mahadwaseem123** [comment]
Hi @SRS-WRKS , can you have a look at above PR? I tried to implement what you were looking for.

**Comment by SRS-WRKS** [comment]
@mahadwaseem123  You have to ask @breck7 , sometimes the response is slow because of work or other commitments/priorities.
