### ISSUE TITLE
Add advanced search

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#121]
https://github.com/breck7/pldb/discussions/120

**Comment by mahadwaseem123** [comment]
Hi @breck7 , I want to try working on this issue but have some questions around it.

1-Can we use any external js library for advance search? 
2-How much time may I spend on this feature?

Any suggestions will be really helpful for me.

**Comment by breck7** [comment]
Hi @mahadwaseem123 no I don't think we should use an external library.

I think we should study how VS Code and Sublime Text have advanced search, and just copy theirs. Basically probably just add Regex search and operators like OR/AND/ et cetera.

Spend as much time as you want. It's an interesting problem

**Comment by mahadwaseem123** [comment]
Thanks a lot @breck7 , I will work on this.

**Comment by mahadwaseem123** [comment]
Hi @breck7 , I attached some screenshots for your reference.

**Comment by SRS-WRKS** [comment]
related issue ? 
https://github.com/breck7/pldb/issues/220 

Should certain keys like compilesTo and featureKeyword be treated specially they could to act like tags for searching and enhance the end user experience.

**Comment by breck7** [comment]
I'm going to close this for now and reopen later
