### ISSUE TITLE
site directory clean after build

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#123]
Note: Thanks to Mr Mahad Waseem , for bringing this to attention 

The command npm run clean does not seem to remove generated html and (generated) scroll files.

The following shell code removes them 
`BUILT_SITE_LIST=$(git status --ignored | sed 's/^[ \t]*//' | grep '^site/.*' )`
`for $BUILT_SITE_FILE in $BUILT_SITE_LIST; do rm "$BUILT_SITE_FILE" ; done
`

Operating system specific shell script seems to be required since  command `./node_modules/scroll-cli/scroll.js where`  lists all scroll files in users home directory (?) with no output customization options.

**Comment by breck7** [comment]
nice work @mahadwaseem123 and @SRS-WRKS!

This is a good idea (https://github.com/breck7/scroll/issues/66). Looking into it now

**Comment by SRS-WRKS** [comment]
Fixed.
