### ISSUE TITLE
broken link on rankings algo explanation page

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#124]
https://pldb.com/pages/the-rankings-algorithm.html

thanks to patrick for the report

**Comment by mahadwaseem123** [comment]
Hi @breck7 , can you send me the correct link? I will fix the broken link with the correct one.

**Comment by mahadwaseem123** [comment]
Hi @breck7 , correct link required to be replaced.

**Comment by celtic-coder** [comment]
Hi @mahadwaseem123,

Breck (@breck7) would need to verify this, but I believe that the link to the source code for the ranking algorithm is: https://github.com/breck7/pldb/blob/main/code/Folder.ts#L539-L544

Kind Regards,
Liam

**Comment by breck7** [comment]
I think you may have been right @celtic-coder but for some reason I'm showing the rankings method at line 158: https://github.com/breck7/pldb/blob/38df473b675c4d48a0d9c1c6fdded9df27953c39/code/Folder.ts#L158

This is such a common request that perhaps it's worth it to create a static version of that method and include it in a separate file. Okay I'll do that now

**Comment by breck7** [comment]
ok the link should now point to: https://github.com/breck7/pldb/blob/main/code/Rankings.ts

**Comment by mahadwaseem123** [comment]
Hi @breck7 , can we close this issue?

**Comment by breck7** [comment]
ask for forgiveness @mahadwaseem123 , not permission ;)

**Comment by mahadwaseem123** [comment]
Hi @breck7 sorry didn't get the previous comment, this issue is completed right?

**Comment by celtic-coder** [comment]
Hi @mahadwaseem123, 

I think what Breck (@breck7) wants us to do is to go ahead and make what changes  (including closing issues) that we think is necessary. No need to ask permission. He is trusting us to make the correct decisions.

Even if a mistake is made, it is not as if it will cause a huge customer impact or lose millions of dollars in revenue. Just admit to the mistake, learn from it and move on.

So, keep moving forward and keep learning! 😄 

Kind Regards,
Liam

**Comment by celtic-coder** [comment]
👍
