### ISSUE TITLE
Broken Youtube Link at Blog Page

### ISSUE THREAD

**Issue by mahadwaseem123** [breck7/pldb#127]
Hi @breck7 , there is one broken youtube link at https://pldb.com/posts/wefunder.html

**Comment by breck7** [comment]
https://www.youtube.com/watch?v=yogvgmK2L4g

**Comment by mahadwaseem123** [comment]
Hi @breck7 , the link was actually fine but it was not used properly as the Iframe supports only embedded link. It took me a bit to understand but now it is working fine. Posted the root cause here so may be it can help someone else too.

**Comment by breck7** [comment]
nice work @mahadwaseem123 !
