### ISSUE TITLE
Unable to Access the Blog tab. 

### ISSUE THREAD

**Issue by rkimera94** [breck7/pldb#129]
@breck7  - When I try accessing the blog tab on the site: I get this error on my local server. 
Cannot GET /site/posts/index.html 
It seems it's not complying index. scroll(index.scroll has no index tags to compile).

**Comment by mahadwaseem123** [comment]
Hi @rkimera94 @breck7 , this may be not the actual resolution but you will be able to access the blog by going to directory pldb/site/posts/ and then run the command pldb/.node_modules/scroll-cli/scroll.js  build. It will compile the .scroll files. Hope it helps.

**Comment by adriantintpilver** [comment]
Hi @rkimera94 , Running pldb in a docker (instructions for this way are in the principal readme), this error no be there and you can navigate BLOG normaly

**Comment by rkimera94** [comment]
Thanks, @adriantintpilver  let me check it out

**Comment by SRS-WRKS** [comment]
@rkimera94   Is this issue solved ?

**Comment by rkimera94** [comment]
I used  scroll-CLI compile:
 I ran this command `root_dir/pldb_dir/node_modules/scroll-cli/scroll.js build`  in the posts directory pointing to the scroll-cli compile.

**Comment by rkimera94** [comment]
@SRS-WRKS @adriantintpilver  the issue is solved I can now access the blog sites. Thanks

**Comment by SRS-WRKS** [comment]
@rkimera94 Closed as requested.
