### ISSUE TITLE
HOWTO generate database/sortTemplate.txt from database/grammar/ sub directory

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#135]
database/sortTemplate.txt seems to be needed for pldb rather than treebase.  Is there a way people can generate database/sortTemplate.txt from a valid database/grammar/ sub directory. It would be really useful for database contributors.

currently how is such a useful file generated ?

**Comment by breck7** [comment]
I write that file by hand currently.

It is a great question. I feel like we are missing a pattern there, but I haven't figured it out yet.

It's been super useful. Before we had that things were a mess.

**Comment by SRS-WRKS** [comment]
Running npm build on a directory containing treebase files (https://treebase.treenotation.org/) should ideally auto generate it, if there was no error in database grammar, etc.

**Comment by SRS-WRKS** [comment]
Answered.
