### ISSUE TITLE
string fileExtension pldb being ignored in database/things/ directory during build

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#137]
The build system seem to try to build even non pldb files in database/things/ while database/grammar/root.grammar Line 8 specifies 

`string fileExtension pldb`

Warning about unnecessary files in database/things/  is acceptable , but building all files seem to defeat the purpose of the grammar file entry.

**Comment by breck7** [comment]
Great point @SRS-WRKS ! You're right it's confusing that we have that line and then ignore it during build.

**Comment by SRS-WRKS** [comment]
@breck7 : This could be a central feature to support multiple tables . Imagining multiple sortTable.txt files and multiple *db.json files being generated would be an awesome addition.

**Comment by breck7** [comment]
> Right now jtree supports a single database only (in a single database/ directory subtree) am i right ?

Yes.

> This could be a central feature to support multiple tables . Imagining multiple sortTable.txt files and multiple *db.json files being generated would be an awesome addition.

I agree. Do you think it should be done using file extension? One extension per table?

**Comment by SRS-WRKS** [comment]
@breck7 , thanks for the reply that too on a weekend. It means soo much :)

It depends on how you want to support other products and architecture along the same lines.

Supporting Berkeley DB (a flat file structure) would mean supporting things as diverse as openLDAP/Active directory as import/export options.  Support for SQL export already exists, if i am not mistaken.

But command line tools like CAT can support merging files quiet easily too. So there are tradeoffs, @celtic-coder mentioned supporting pldb on windows and filed bug reports about the same.

 You also said before that you don't like docker, because you prefer bare metal :) 

If you decide to support flat file structures, you can think of parsers as supporting both compilers ( pldb )and file processing commands like AWK/perl (???) .

No one has a golden rule, that supporting file parsers has to be limited to compilers :)

I am a wannabe code grunt (your github description is misleading :) ), you decide the architecture because i don't know The Public Domain Publishing Company well enough.

Good day.

**Comment by breck7** [comment]
I am going to close this now as I will probably fix as part of https://github.com/breck7/pldb/issues/59
