### ISSUE TITLE
Duplicate Languages/Entities in database/things 

### ISSUE THREAD

**Issue by mahadwaseem123** [breck7/pldb#138]
Hi @breck7 , while doing appeared keyword coverage increase issue, I came across the fact that there are some duplicate pldb file in database/things for same languages. This could also impact coverage too. What you suggest?

**Comment by breck7** [comment]
Great question @mahadwaseem123 . It happens! Merge the dupes and send a pull request.

Here's an example: https://github.com/breck7/pldb/commit/6ab84b2e08d25843629e55ce8145bd62a26c2046

(delete the one with the worse filename and move any facts from it to the other one)
