### ISSUE TITLE
Make ScrollSet for Creators

### ISSUE THREAD

**Issue by celtic-coder** [breck7/pldb#139]
Hi Breck (@breck7),

I would like to update the Wikipedia entries for the [language creators](https://pldb.com/lists/creators.html). However, in order to do so, I would need to know if the "[creators.tree](https://github.com/breck7/pldb/blob/475e792ce52043d286d472795f09a866e374e9b1/site/lists/creators.tree)" file  is auto-generated?

Also, it looks to have 59 Wikipedia records, but the corresponding HTML file has only 56 corresponding links, so there is a discrepancy somewhere in how the HTML is generated. If there is a problem, I will resolve this as part of the update.

I would like to get working on this, so any pointers would be appreciated.

Thanks!
Liam

**Comment by breck7** [comment]
Aloha @celtic-coder ! Great idea. It is not auto generated.

**Comment by breck7** [comment]
I had an idea once that maybe each of these entries should be a full file (https://github.com/breck7/pldb/tree/main/site/users), but I think that would be premature optimization, and we could probably get very far just by updating the creators.tree file.

**Comment by celtic-coder** [comment]
Thanks to Hassam (@hassamalhajaji) for PR #271 (commit https://github.com/breck7/pldb/commit/3a159f5b9f9ec30c98c993cbc6f9925ac4072eac) on October 29th, to cover most of the Top 100 of the [Language Creators](https://pldb.com/lists/creators.html).

**Comment by breck7** [comment]
Just linking this to:
https://github.com/breck7/pldb/issues/68

I think the way to go is to make "creators" a Scroll dataset. https://scroll.pub/blog/datasets.html

I might play with that later to see if it works well.

**Comment by breck7** [comment]
https://github.com/breck7/pldb/issues/257

**Comment by breck7** [comment]
Okay, now that we have ScrollSets (https://scroll.pub/blog/scrollsets.html), the creators stuff is much better.

I just added some more info to seed, but should be quick to get a lot of info in there now.
