### ISSUE TITLE
Add indeed.com jobs numbers for top 250 langs

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#148]
The `indeedJobs` keyword should be present on at least the top 250 langs.

![Screen Shot 2022-09-30 at 3 26 24 AM](https://user-images.githubusercontent.com/74692/193279799-1fc9a098-093b-4dd2-b33e-0c0c870b0163.png)

**Comment by rkimera94** [comment]
hi @breck7  i have added indeed job numbers to some langs [PR](https://github.com/breck7/pldb/pull/198)

**Comment by rkimera94** [comment]
Kindly, review if I should proceed with all the other top 250 langs
