### ISSUE TITLE
Free ebooks page

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#151]
We should have a page with the best free computer science ebooks. Do we have that yet?

If not, here's one to add:

https://bertrandmeyer.com/2022/09/28/introduction-theory-programming-languages-full-book-now-freely-available/

**Comment by celtic-coder** [comment]
Another computer science list:
https://github.com/EbookFoundation/free-programming-books/blob/main/books/free-programming-books-subjects.md#computer-science

**Comment by rkimera94** [comment]
very right @breck7  and @celtic-coder  let work on this

**Comment by rkimera94** [comment]
<img width="1390" alt="Screenshot 2022-09-30 at 19 24 10" src="https://user-images.githubusercontent.com/54355787/193314997-0b013e39-5580-4746-b471-8c3ad7cb854d.png">

@breck7  and @celtic-coder  would this be fine?

**Comment by breck7** [comment]
@rkimera94 I wouldn't broaden it to "Resources". I would keep it very specific on ebooks. That way you can drop the type column. I would also add a Year column and column for Publisher and Country.

**Comment by rkimera94** [comment]
Okay let me keep it ebooks, @breck7  then rename author to publisher, then add the year column. thanks for the feedback.

**Comment by rkimera94** [comment]
@breck7  I have made the changes on the ebook's list,  here is my [PR](https://github.com/breck7/pldb/pull/154).
