### ISSUE TITLE
In CSV docs, computed columns should link to the function in the File.ts file that computes them

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#159]
For example, the last column for `exampleCount`:
![Screen Shot 2022-09-30 at 12 58 13 PM](https://user-images.githubusercontent.com/74692/193367170-e59fc760-1fdf-4f1f-bf8e-4bbe19522f05.png)

should say `exampleCount()` and link to the following:

https://github.com/breck7/pldb/blob/97ef6c487a87ede910ffd252e5e97036ef53a9a9/code/File.ts#L204

**Comment by breck7** [comment]
Thanks to PV for bringing this up!

**Comment by mahadwaseem123** [comment]
Hi @breck7 , I will work on this.

**Comment by mahadwaseem123** [comment]
Hi @breck7 , this is resolved in the above PR. Kindly have a look.

**Comment by mahadwaseem123** [comment]
Hi @breck7 , this issue is fixed in #192 . Kindly check and let me know if you like it. As the changes were in csvImports.scroll file and it is in git ignore, I have to forcefully add the complete updated file. Let me know if we can use different approach here or if this is fine. Thank you.

**Comment by breck7** [comment]
Done
