### ISSUE TITLE
Improve Binary Notation page

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#161]
https://pldb.com/languages/binary-notation.html

**Comment by SRS-WRKS** [comment]
Are more details required ??

**Comment by breck7** [comment]
@SRS-WRKS  It's just a clear code smell that binary notation (the mother of all computer languages) is ranked in the 700's. It should probably be ranked number 1. Which means we are missing a lot of data on it. A lot of links, information about papers, books, what langs influenced it and it influenced, etc

**Comment by breck7** [comment]
When binary notation is ranked number one (or at least very close to number one), then we will know we have built a good site ;)

**Comment by mahadwaseem123** [comment]
Hi @breck7 , I have got your point. I added an example, book and publication as an improvement starting point. Will be adding more things in next PR's.
