### ISSUE TITLE
database request key type alias or redirect

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#163]
The wikipedia page https://en.wikipedia.org/wiki/Coral_66 redirects to https://en.wikipedia.org/wiki/CORAL. 

The closest way to have the same functionaltiy in pldb is to have a pldb file `database/things/coral.pldb ` with just the following entries : 

`title coral-66`
`aka coral`
`related coral`

Would such a short file be acceptable ?

Otherwise the wikipedia and other references look out of place or would be duplicated.

**Comment by breck7** [comment]
Good question. @celtic-coder do you have an opinion on these kinds of situations?

**Comment by SRS-WRKS** [comment]
Can a pldb file exist with the following name in database ??

`title Foo
aka Bar`

If so, this issue could be closed.

**Comment by breck7** [comment]
Okay I think we should not have pages just for a redirect. The aka field should be used for search/autocomplete.
