### ISSUE TITLE
make search autocomplete <a tags>

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#164]
If these were a tags, then a user could right click them and open a bunch in new tabs:

![Screen Shot 2022-10-02 at 4 37 50 AM](https://user-images.githubusercontent.com/74692/193459837-146840d7-5742-462e-b2a6-2090a18925df.png)

**Comment by adriantintpilver** [comment]
One thing remains pending in this issue, which is adding the "oncontextmenu='return false;'" to the body of the index.html. With this addition, the context menu is not shown directly. But I couldn't find where to put this in the index.scroll or others .scroll for when be generating the index.html, keep this code in the html body tag. I've been trying a lot but I didn't get it.
In any way, as it is, it works, but on the page from where we launch the search, it opens the contextual menu after launching the link to the new tab.

**Comment by breck7** [comment]
Thank you for the work @adriantintpilver ! This was actually a really hard one. Your work helped me figure it out. I'm pushing a commit now. There's still one minor bug maybe you can help me solve it.

**Comment by breck7** [comment]
Still a little messy. I have some cleanup to do.
