### ISSUE TITLE
how to run https://build.pldb.com/search in local PLDB project

### ISSUE THREAD

**Issue by adriantintpilver** [breck7/pldb#177]
Talking to several of those who work on this project, no one has managed to run to locate the search part of the project that calls the SEARCH function (https://build.pldb.com/search).
The idea of this issue is to investigate how to do this and then make a documentation that allows everyone to run 100% of the project locally.
Additionally, it would be ideal to have this in a docker to make it even easier.

**Comment by breck7** [comment]
Thanks very much for bringing this up @adriantintpilver !

I don't see us using docker as we like to run as close to the metal as possible but it's a good point that you brought up there.
