### ISSUE TITLE
add instructions somehwere on how to use roapi with our dataset

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#181]
https://github.com/roapi/roapi

**Comment by whatrocks** [comment]
I think so. You can try it now by running this [REPL](https://replit.com/@whatrocks/pldb-roapi#README.md) and trying this curl command:

```
curl -X POST -d "SELECT title, appeared from pldb where appeared < 1980 LIMIT 2" https://pldb-roapi.whatrocks.repl.co/api/sql | jq
```

**Comment by whatrocks** [comment]
<img width="1145" alt="Screen Shot 2022-10-05 at 11 08 20 PM" src="https://user-images.githubusercontent.com/482482/194227086-2bf0076e-fe46-4439-8282-6c43757f48a0.png">

**Comment by breck7** [comment]
It looks like the repl demo is longer up.

Anyway, gonna close this for now but I expect we'll reopen at some point.
