### ISSUE TITLE
should we have a page with a list of college classes that teach programming language design?

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#184]
https://www.cs.umd.edu/class/fall2022/cmsc430/index.html

**Comment by mahadwaseem123** [comment]
Good idea @breck7. May I work on it?

**Comment by mahadwaseem123** [comment]
Hi @breck7 , did you get a chance to check it?

**Comment by SRS-WRKS** [comment]
Universities and colleges around the world vary in Naming convention. For example University of London has Member institutions (https://www.london.ac.uk/ways-study/study-campus-london/member-institutions) . while university of California has 9 campuses with distinct names (https://admission.universityofcalifornia.edu/campuses-majors/). How would the value of the key in pldb files look like, How can it be validated using grammar ??

**Comment by mahadwaseem123** [comment]
Hi @SRS-WRKS , I used static webpage course links to sites which are teaching programming language designing. As you can see in my above PR but I don't know if it fulfilled the requirement.

**Comment by SRS-WRKS** [comment]
You will have to ask @breck7 , sometimes the response is slow because of other work/commitments/priorities. 
All i know is lists are usually generated using databases in this project.

**Comment by mahadwaseem123** [comment]
Yes @SRS-WRKS , totally understand.
