### ISSUE TITLE
How to run PLDB in a local environment

### ISSUE THREAD

**Issue by adriantintpilver** [breck7/pldb#185]
I found a way to run locally in docker by adding the line:

"start": "site/index.html",

to the package.json.

But I understand that there has to be a way without doing this to run it.

It would be good to upload the instructions to this issue so that everyone can do it the right way. It could even be added to the project's main readme.md.

**Comment by breck7** [comment]
Good question @adriantintpilver!

2 ways:

1. Run `npm run build` then open `site/index.html`. This will just be the static site (search will not work).
2. Run `npm run local`. This will be the Express app running on localhost with search.

**Comment by adriantintpilver** [comment]
When testing npm run local, the /ignore directory of some lines of the package.json is giving me an error
I paste the error log:

--- log ---

# npm run local

> local
> ./code/BuildServer.js startDevServer

node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/app/pldb/ignore/buildServerLog.tree'
    at Object.openSync (node:fs:594:3)
    at Object.writeFileSync (node:fs:2207:35)
    at Function.Disk.write (/app/pldb/node_modules/jtree/products/Disk.node.js:18:36)
    at Function.Disk.touch (/app/pldb/node_modules/jtree/products/Disk.node.js:12:55)
    at Object.<anonymous> (/app/pldb/code/BuildServer.js:24:6)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/app/pldb/ignore/buildServerLog.tree'
}
#

**Comment by breck7** [comment]
Wow! Sorry about that. Thank you for the clear report @adriantintpilver ! I was able to reproduce and submitted a fix. Can you try again?

**Comment by adriantintpilver** [comment]
You were the ONE!! now works!!! many thanks. 
I am running this in a docker, here are the steps to put this to run in a docker:
later if you are interested you could make a docker compose image to make it even easier.

-------------------------------------------
-- Run PLDB in docker

docker run -it -d -v /c/AndelaWork/pldb:/app -p 4444:4444 --name pldbnode node:16 bash

-- into docker interactive session run the follow:

git clone https://github.com/breck7/pldb
cd pldb
npm install .
npm run tsc
npm i -g cloc
npm run build
(Optional run TESTS): npm run test
(Following updates): npm run format
npm run local

**Comment by breck7** [comment]
Wow very cool @adriantintpilver ! Can we add the docker instructions someplace in the docs? I will never use Docker as I spent my 20's mastering thousands of esoteric linux commands but there's no reason that other people must suffer like that if they prefer Docker ;)
