### ISSUE TITLE
First 'git pull' is painfully slow

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#189]
Probably b/c of the github.pldb.com branch?

**Comment by SRS-WRKS** [comment]
Trying to overhauling the repository as a relatively new contributor, is too risky for me :) #EYE_cantCompetewithBreck

**Comment by SRS-WRKS** [comment]
Duplicate of Issue #75

**Comment by SRS-WRKS** [comment]
@breck7 : The issue seems to be https://stackoverflow.com/questions/11050265/remove-large-pack-file-created-by-git 


The culprit file seems to be .git/objects/pack/pack-b111d543e833814c47944a85bce47cd1221e870e.pack

**Comment by SRS-WRKS** [comment]
@breck7 : The following commands should have worked. It does decrease the time required to download, in local test.
Note: test conducted on git version 2.30
The following commands were executed. 
`git filter-branch --index-filter 'git rm -r --cached --ignore-unmatch pack-b111d543e833814c47944a85bce47cd1221e870e.pack' --prune-empty
 git for-each-ref --format='delete %(refname)' refs/original | git update-ref --stdin
 git reflog expire --expire=now --all
 git config pack.windowMemory 10m #only needed if error message error: pack-objects died of signal 9059 is printed before failing.
 git config pack.packSizeLimit 20m # only needed if error message error: pack-objects died of signal 9059 is printed before failing.
 git gc --aggressive --prune=now
 git push --force --all`

The repository is here https://github.com/SRS-WRKS/pldb_repo_minified

**Comment by celtic-coder** [comment]
Very good research Hari (@SRS-WRKS)! Well done! 👍

**Comment by SRS-WRKS** [comment]
The best results seem to come from the following, pereodic purgin of github.pldb.com branch

` git push origin --delete github.pldb.com

 git branch --delete origin/github.pldb.com

git branch --delete github.pldb.com

git branch --delete --remotes origin/github.pldb.com

git fetch origin --prune

git filter-branch --index-filter 'git rm -r --cached --ignore-unmatch pack-0f5756d5527ecda27b539906a9a83974a0d2a213.pack' --prune-empty

git for-each-ref --format='delete %(refname)' refs/original | git update-ref --stdin

git reflog expire --expire=now --all

git config pack.windowMemory 10m

git config pack.packSizeLimit 20m

git gc --aggressive --prune=now

git push --force --all`

git pull can be completed in a few minutes and the repository size decreases too.

Link in https://github.com/SRS-WRKS/SRS-WRKS-pldb_repo_minified-__1

**Comment by breck7** [comment]
Great research @SRS-WRKS ! I'm going to sleep on this one.

**Comment by breck7** [comment]
Yikes! 191 seconds for a fresh git pull. Should be >10x faster.

<img width="672" alt="Screen Shot 2022-11-12 at 6 38 03 AM" src="https://user-images.githubusercontent.com/74692/201479233-f2d23aba-cca1-47f4-b764-0f129ba29cc2.png">

Going to follow your leads now @SRS-WRKS .

**Comment by breck7** [comment]
Ah well I am on a relatively slow Internet connection right now! Thats why mine took so long (I just deleted the github.pldb.com branch, so we should avoid those problems now).

Just tried on a fast cloud machine and got 4 seconds for the first pull! Case closed. Thanks @SRS-WRKS !

<img width="521" alt="Screen Shot 2022-11-12 at 6 42 49 AM" src="https://user-images.githubusercontent.com/74692/201479461-5485235e-c1d9-4a1f-a420-cb83b27142ca.png">
