### ISSUE TITLE
Full text search URL is missing in autocomplete

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#196]
<img width="421" alt="Screen Shot 2022-10-06 at 12 34 11 PM" src="https://user-images.githubusercontent.com/74692/194402894-31282999-90e4-4823-8b1a-85c5c50ace70.png">

**Comment by adriantintpilver** [comment]
I love these kinds of problems.
I take this

**Comment by adriantintpilver** [comment]
Hi Breck,

I saw this, right now the search link works, whit any mouse button, and the links carry the search characters, and the search work fine.
Please tell me if you still see the error.

Thanks!
Regards!

**Comment by breck7** [comment]
I am still seeing the error. It only happens when you hover over the "Full text search"
<img width="285" alt="Screen Shot 2022-10-07 at 7 17 34 AM" src="https://user-images.githubusercontent.com/74692/194575172-c6ffc1f6-cfe7-498e-9026-bb5bb82a038b.png">

**Comment by adriantintpilver** [comment]
Hi Breck,

Sorry for the mistake, you don't say you change the combo to <a tags, my bad.
Right now it is solved.

Thank you!
Regards

**Comment by mahadwaseem123** [comment]
Hi @breck7 , is this issue fixed or may I work on it?

**Comment by adriantintpilver** [comment]
Hi @mahadwaseem123 this bug y fixed in the las commit. Thanks

**Comment by breck7** [comment]
Not fixed. Still happens.

**Comment by adriantintpilver** [comment]
Hi Breck,

This is fixed in the las commit but, that commit is very dirty. Rigth now clenan that and do a new pull request with this fix. 
Please check and tell me.

Thanks a lot.
Regards.
