### ISSUE TITLE
Add multiple documentation keyword support 

### ISSUE THREAD

**Issue by mahadwaseem123** [breck7/pldb#210]
There can be multiple docs of a single language and PLDB should support multiple docs.

**Comment by mahadwaseem123** [comment]
Hi @breck7 , I enabled multiple documentation support. Here is the PR #214

**Comment by SRS-WRKS** [comment]
Reference in commit f38a41fa59920ddacacc20809fbe2006f92b4b8f and seemed to be accepted should this be closed ?

**Comment by mahadwaseem123** [comment]
Yes @SRS-WRKS right. I guess I don't have github permissions to close an issue as I can not see any option at my end. I have rights to open an issue but can't see any option to close an issue. If you have, you can close this issue.

**Comment by SRS-WRKS** [comment]
@mahadwaseem123 Thank you for the update. 

@breck7 Can this issue be closed ?? Seems to be done

**Comment by breck7** [comment]
@mahadwaseem123 you should be able to close issues now. thanks for letting me know.

**Comment by SRS-WRKS** [comment]
@breck7 Thanks for clarification. Closed.
