### ISSUE TITLE
domainName node for defunct then revived domains

### ISSUE THREAD

**Issue by lngns** [breck7/pldb#211]
When editing enso-lang.pldb, I noticed it documented a 2022 registration for enso-lang.org, despite it being a re-registration, the first being in 2011 and actually related to the language.  
When it comes to such archival, how do we deal with that?

**Comment by adriantintpilver** [comment]
Hi @lngns ! 

I see we have a duplicated enso (enso-lang.pldb and enso.pldb) . I think it is necessary to merge two files in one only file.

About the date, i see reference in diferente articles in internet the registered year is --> 2001

I am going to do the unification in one file.

**Comment by lngns** [comment]
@adriantintpilver 
Those are two different languages, one is from 2011 and the other from 2017 after a name change from Luna.

You'll also see we have 3 indexed languages called 'Broccoli' lol.

**Comment by adriantintpilver** [comment]
i see this. are very similar really. Is really confused have different languages with the same name. 

May be is posible put the year in the name, become enso_2011 and enso_2017, and use this semantics for each case of equal names, and this way we differentiate one from the other.

i see the brocolis things, is funny and madness :D

**Comment by SRS-WRKS** [comment]
@lngns @adriantintpilver , a link to archive.org, if it exists !!!
Registrars and archive.org don't delete things, just like big tech :)

An archive.org link if it exists or a link to domain name registrar. referential integrity to databases is always important apparently

**Comment by breck7** [comment]
Okay sorry I missed this one, but it seems at https://pldb.com/languages/enso-lang.html we show 2011, so I'm assuming this was fixed and am going to close.
