### ISSUE TITLE
Add search to Lanagues tab(Top 500 programming languages)

### ISSUE THREAD

**Issue by rkimera94** [breck7/pldb#218]
<img width="917" alt="Screenshot 2022-10-14 at 11 22 07" src="https://user-images.githubusercontent.com/54355787/195852137-e41ffe32-ba42-4ecd-b33a-01837fafd64a.png">

@breck7  Trying to work on a search for the list of programming languages. 
 Inquiry: How to fix the position of the search to appear on top of the table list?

**Comment by breck7** [comment]
Wow weird! Thank you for bringing this to my attention @rkimera94 !

This page did not used to look like this. Even now it seems to look find in Safari but broken in Chrome:
<img width="1353" alt="Screen Shot 2022-10-14 at 6 07 09 AM" src="https://user-images.githubusercontent.com/74692/195854600-0affc7f8-790b-4094-be75-e58104a71bcc.png">

Anyone know what's going on? Maybe something in Chrome's CSS engine changed?

**Comment by rkimera94** [comment]
![Uploading Screenshot 2022-10-14 at 16.17.21.png…]()
yes, you are right @breck7. With Safari, it works fine.

**Comment by mahadwaseem123** [comment]
Hi @breck7 @rkimera94 , I have added the search bar. It is on correct place now. 
<img width="805" alt="Screenshot 2022-10-21 at 10 55 13 PM" src="https://user-images.githubusercontent.com/36690888/197260737-97a6f414-7804-4253-b397-d603f4e57256.png">
