### ISSUE TITLE
add language: https://github.com/tlocke/zish

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#221]

**Comment by adriantintpilver** [comment]
Done, added to database

**Comment by breck7** [comment]
I don't see it @adriantintpilver . Did you send a pull request?

**Comment by adriantintpilver** [comment]
strange, I did it... but I think that when putting the URL of another github repo in the commit sumary something went wrong whit the link here.

**Comment by adriantintpilver** [comment]
The commit is here --> https://github.com/adriantintpilver/pldb/commit/f404e0160c4f9f197ee8dc510b70b392a88c9a7d

**Comment by SRS-WRKS** [comment]
@breck7 : was this added, should i close this issue ?

**Comment by celtic-coder** [comment]
I created and merged a PR, as noted above. Thanks Adrian (@adriantintpilver) for your commit - https://github.com/adriantintpilver/pldb/commit/f404e0160c4f9f197ee8dc510b70b392a88c9a7d!
