### ISSUE TITLE
Feature Request: REPL environment and cli tools for pldb grammer

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#223]
scroll has a nice repl envirnoment https://try.scroll.pub/, pldb grammar/treebase notation should have the same too !! 

also scroll has cli tools, pldb treebase notation does not seem to have the same.

**Comment by breck7** [comment]
Hi @SRS-WRKS we have this: https://jtree.treenotation.org/designer#url%20https://pldb.com/pldb.grammar

Did I not add a link to that anywhere? Sorry if not!

I also have a branch refactoring that Designer app as it wasn't engineered great but just sort of evolved organically.

**Comment by breck7** [comment]
If there's not a link to that anywhere in the readme or docs, would you mind adding one?

**Comment by SRS-WRKS** [comment]
@breck7 Sure thing, ill add it. But where should i add it ? To jtree repo README ??

**Comment by breck7** [comment]
Where would you expect it to be @SRS-WRKS ?

**Comment by SRS-WRKS** [comment]
Link https://jtree.treenotation.org/designer#url%20https://pldb.com/pldb.grammar , In the readme of jtree .

A separate file mentioning list of DSL as a  seperate file in jtree where there is mention of cli tools, repl environment, etc for each DSL included as part of readme of jtree

**Comment by SRS-WRKS** [comment]
@breck7 jtree.treenotation.org/designer lists many example languages , all the languages have readmes but none of the readmes require a link to the example language repository. or at the very least a referenceURL for explaining grammar and a watchURL for latest version information. 

some of the example languages repository has been deleted..

Also an ability to load grammar using upload button would be really helpful too.

Getting back on topic, it does not seem to list PLDB grammar

**Comment by SRS-WRKS** [comment]
Continued in https://github.com/breck7/jtree/issues/159
