### ISSUE TITLE
Should database/sortTemplate.txt support database nodes rename, addition and deletion information

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#239]
https://peps.python.org/ has information about addition or deletion or rename information
>>  npm run format gives following warnings.

` npm run format

> format
> ./code/SiteBuilder.js formatDatabase

Running formatDatabaseCommand:
sortTemplate is missing "summary"
sortTemplate is missing "summary"
sortTemplate is missing "summary"
` 

It could be as simple as logging git diff HEAD HEAD~5 database/sortTemplate.txt for every change to the file.

**Comment by breck7** [comment]
I don't think we have a keyword 'summary'.

**Comment by SRS-WRKS** [comment]
Thank you for replying, most projects don't.

Sorry, 
- firstly i am learning:
-  this was about the lack of changelogs for sortTemplate.txt , with inspiration from  https://en.wikipedia.org/wiki/Changelog and https://keepachangelog.com/en/1.0.0/ 
A lot of things are nice.
The lack of version information, selective field selection ,etc could hamper people using this nice technology.

**Comment by SRS-WRKS** [comment]
Closed as it would be moved to discussion
