### ISSUE TITLE
should we have a field like 'annualReport`?

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#247]
for example, for CSS we might have:

```
annualReport
 2022 https://web.dev/state-of-css-2022/
```

**Comment by rkimera94** [comment]
@breck7  Great idea! 
how about just indicating the sites where the annual reports/surveys can be found for the different software survey platforms 

for example [stateofjs](https://stateofjs.com/en-us/)  it has js, CSS, Graphql 

python: https://www.python.org/psf-landing/

There someone can pick interest in the different reports say 2022,2021 for a survey comparison

**Comment by rkimera94** [comment]
I am working on this

**Comment by rkimera94** [comment]
hi Breck @breck7  trying to work on this issue 
Kindly review if am on the right direction 
[PR](https://github.com/breck7/pldb/pull/260)

**Comment by rkimera94** [comment]
@breck7   I have made some changes, ready for review! I have introduced 4 classes through the annualReports key. 
[PR for review ](https://github.com/breck7/pldb/pull/264)

The classes: 
eventsPageUrl
releaseNotesUrl
officialBlogUrl
annualReportUrl
Which should be specified for the URL type/page type

**Comment by rkimera94** [comment]
Still failing some tests! which i need to check

**Comment by rkimera94** [comment]
@breck7   is  it okay to close this issue or there is more to add  ?
