### ISSUE TITLE
pldb build system compilation stop during error and error codes

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#249]
The pldb build system does not stop compilation in case of typescript errors but does stop compilation in case of some grammar key related issues (currently know include writtenIn and related keys).

The error codes of such commands also seem to be unreliable indicator or build success.

**Comment by breck7** [comment]
okay these are good points. we can improve. thanks @SRS-WRKS !

**Comment by SRS-WRKS** [comment]
@breck7 Do you want to assign this to someone (may the suggester :) )  ??

**Comment by breck7** [comment]
The build system has been largely removed.
