### ISSUE TITLE
add `emailList` field?

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#250]
https://github.com/breck7/pldb/commit/c1590cef8b623ecbde8fbdfb7736bdb4144e797c#r87637513

**Comment by breck7** [comment]
lots of these languages have email lists and thats how many of them started. we should probably record that.

**Comment by mahadwaseem123** [comment]
Sure @breck7 , will be working on this.

**Comment by celtic-coder** [comment]
Good work, Mahad (@mahadwaseem123)! 👍

**Comment by mahadwaseem123** [comment]
Thanks a lot @celtic-coder
