### ISSUE TITLE
Creators page should have links to Creator's homepage, github, twitter, and wikipedia page (if any/all of those are available)

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#257]
https://pldb.com/lists/creators.html

**Comment by SRS-WRKS** [comment]
@breck7 : creators.tree then should have grammar supporting homepage, github, twitter, and wikipedia page and the scroll view page should support multi link support for the same. How can someone new to the project achieve the same ??

**Comment by SRS-WRKS** [comment]
@vanshika2910 : As far as i know, Creators.tree is not auto-generated (https://github.com/breck7/pldb/issues/139) . 
You might want to introduce yourself to scroll (https://github.com/breck7/scroll) before you want to get started.

**Comment by SRS-WRKS** [comment]
Do you want to contribute using Web UI or are you comfortable with other ways of contributing ?

**Comment by SRS-WRKS** [comment]
Do you want to contribute using WebUI is different from working on the webUI.
If you want to really contribute only code, please look at other projects from breck7 (github.com/breck7/)
