### ISSUE TITLE
Suggested importer: Sample programs in every language

### ISSUE THREAD

**Issue by celtic-coder** [breck7/pldb#26]
Hi Breck (@breck7),

Back in mid-July, you added the **leachim6** importer ([8fdd117](https://github.com/breck7/pldb/commit/8fdd1178426f1876a5f7f343eda1f2427b13e38a)) for the "hello-world" programs.

Might it also be possible to create an importer for the [Sample Programs in Every Language](https://sampleprograms.io/), a collection started in 2018 by Jeremy Grifski (@jrg94) as part of **The Renegade Programmer** project? At the end of July, the [repo](https://github.com/TheRenegadeCoder/sample-programs) contained 162 languages with 597 code snippets.

Kind Regards,
Liam

**Comment by celtic-coder** [comment]
*The Renegade Coder project.

**Comment by jrg94** [comment]
Sounds like a good idea to me! I have some Python code that locally clones the repo and traverses the existing code base, if that seems helpful to y'all: https://github.com/TheRenegadeCoder/subete

**Comment by breck7** [comment]
I hadn't seen SamplePrograms before, thanks for the pointer @celtic-coder!

Let's add it. I'm on the road so can't look too closely now but should be similar to the leachim6 as you said.

**Comment by breck7** [comment]
I'll leave this open if someone wants to add this.

**Comment by breck7** [comment]
I'm going to close this. but if anyone wants to do it feel free to reopen
