### ISSUE TITLE
good article with good data for us

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#287]
https://web.archive.org/web/20220331041830/https://aspire.eecs.berkeley.edu/2017/06/how-close-is-risc-v-to-risc-i/

**Comment by DeepakKabdwal** [comment]
Can you describe what is the issue and how can I help?
I am just starting out with this.
thanks.

**Comment by breck7** [comment]
Hi @DeepakKabdwal ! This issue was just to look at our Risc pages like https://pldb.com/languages/risc-v.html and add more data. I am going to close it b/c I probably should have added it to discussions, but feel free to add data on Risc to our database if you'd like!
