### ISSUE TITLE
A valid working non empty code/crawlers/github.com/ignore/creds.json

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#295]
How can one create a valid working non empty `code/crawlers/github.com/ignore/creds.json`
 that  does not print warning
`No GitHub token found`

**Comment by SRS-WRKS** [comment]
Read file `code/crawlers/github.com/readme.md`

Read article https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

Run commands:
`mkdir code/crawlers/github.com/ignore/

echo  \'{"apiToken":"TEST-TOKEN","apiUser":"TEST-USER"}\'
`

**Comment by breck7** [comment]
Great work @SRS-WRKS ! Sorry for the lack of docs. Just added this to the readme in that folder
