### ISSUE TITLE
database key writtenIn and database key title values could conflict

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#298]
database key writtenIn seems to accept space separated values of while the key title allows space to be included as value for individual entries. This could lead to conflicts.

**Comment by breck7** [comment]
`writtenIn` should be the permalink (the filename without the extension), not the title.

**Comment by SRS-WRKS** [comment]
I will updated my documentation ( I will give you the link, once it is in a readable state).

Yes but still, valid file names can contain spaces.

you might not use spaces in filenames, but people still get confused.

**Comment by breck7** [comment]
> valid file names can contain spaces.

Wow! Sorry this was a bug. Thank you for alerting me to this. Fixed here: https://github.com/breck7/pldb/commit/113e2d1db0902ab28e411d101dbca8a0d55a51b0

**Comment by SRS-WRKS** [comment]
@breck7 : thanks for the fix. I am closing.
