### ISSUE TITLE
add rosetta (interpeter)

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#300]
https://dougallj.wordpress.com/2022/11/09/why-is-rosetta-2-fast/

**Comment by adriantintpilver** [comment]
added this language whit this PR --> https://github.com/breck7/pldb/pull/304

**Comment by breck7** [comment]
you should be able to close issues now @adriantintpilver !

**Comment by adriantintpilver** [comment]
Thanks for the trust!! i close this issue right now!! :D
