### ISSUE TITLE
Error while building project 

### ISSUE THREAD

**Issue by mahadwaseem123** [breck7/pldb#307]
Hi @breck7 , today after pulling latest changes, npm run build is getting failed and giving this error:
<img width="913" alt="Screenshot 2022-11-12 at 1 34 44 AM" src="https://user-images.githubusercontent.com/36690888/201427182-0375500f-2884-4aaf-90fa-d01fbfbb977d.png">
Do you have any idea about this?

**Comment by breck7** [comment]
Should be fixed. Try pulling the latest.

**Comment by mahadwaseem123** [comment]
Fixed @breck7 , thanks a lot.
