### ISSUE TITLE
Can someone else setup a mirror that auto deploys when we git push?

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#310]
I am going to nuke the github branch to fix https://github.com/breck7/pldb/issues/189.

But that means we have no auto mirror setup when someone git pushes. Can someone setup their own repo and get that going? We can then link to that one.

**Comment by SRS-WRKS** [comment]
@breck7 :

It would be better if you used cloud bucket storage or git large file storage (https://git-lfs.github.com/).

It could either be output of command `git archive` ( open source projects of yester years still release tarballs :) )

or you could use github api to check the latest commits that passed the test and get their zip file archives using github api.


But the build system does not seem to be ready to autodeploy the project just yet. 

Some times the build stops when there are errors, some times it doesn't. 

Error codes/return codes from each build step are not documented. So people wont know when things are successful or when things fail easily, so what is deployed could be a commit you might not be expecting ( as of today when not using githubapi, grepping for certrain things is the only sure way).

Building the project correctly and reliably is required before auto deployment in my opinion.

**Comment by SRS-WRKS** [comment]
You also allow people to edit the project anonymously. People possibly injecting malicious entries is also a security risk.

**Comment by SRS-WRKS** [comment]
A few related build system issues that would need attention even before attempting auto deployment
* https://github.com/breck7/scroll/issues/72
* https://github.com/breck7/scroll/issues/72
