### ISSUE TITLE
Problems with build pldb in local - treeBase.node.js:271 - throw new Error("bad \\r in " + fullPath)

### ISSUE THREAD

**Issue by adriantintpilver** [breck7/pldb#311]
I'm having problems running the build locally, try with node 16 and with the latest version and it is the same, attach build log error.
Run this in a new docker with fresh git clone from pldb:main.
Does anyone have this error too? I heard about suggestion. 
Thanks!

![pldb error build in node 16](https://user-images.githubusercontent.com/114493221/201656926-8267f460-1ff0-4bf2-9731-bf4c2bfebd15.png)
![pldb error build in node 19](https://user-images.githubusercontent.com/114493221/201656932-57b66bc6-bf98-4781-bfcc-31225b311718.png)

**Comment by adriantintpilver** [comment]
I also thought that the first time, so I deleted everything and downloaded everything from scratch, now I'm with a fresh version of main without any changes from my local and it keeps happening.
I'm still investigating

**Comment by celtic-coder** [comment]
Is  ".q.pldb" (with a leading dot), a valid PLDB file?

**Comment by adriantintpilver** [comment]
I thinking the same, but if you delete the ".ql.pldb" file, the error appear in the next file, i had try deleted many file but the error always appear in the first taken file in alphabetical order in things folder. 
Atanch the same error with the next file "05ab1e.pldb"
![pldb error build in node deleted - ql pldb-](https://user-images.githubusercontent.com/114493221/201704148-0315b2ae-3ce1-4cc8-8dc6-e82f8f3c9830.jpeg)

**Comment by adriantintpilver** [comment]
debugging the line 271 from treebase.node.js, and put console log: content.match(/\r/) --> i found "/r" in all lines of all .pldb files, is very extranger.  At each newline find /r/n

![pldb error build log print content match(r))](https://user-images.githubusercontent.com/114493221/201784500-4fcef82c-3a5e-4dda-a5e9-a4356d0e2b10.jpeg)

still work in that

**Comment by adriantintpilver** [comment]
i work ia borrowed computer with a windows, (because mi notebook broken last week), work in docker with shared folder, but if i do the git clone in the folder from the windows side, this error happens, but if you do the git clone in the folder docker side from the command line inside the docker the error don't happen.
I am happy I solved the error, and the conclusion is always the same  --> Fuking Windows!!!! 
Sorry for all this, I think I learned something good and I hope to get my computer back next week.
