### ISSUE TITLE
Issue while building project

### ISSUE THREAD

**Issue by mahadwaseem123** [breck7/pldb#314]
Hi @breck7 , getting below error while building project i.e npm run build
<img width="907" alt="Screenshot 2022-11-16 at 1 23 07 AM" src="https://user-images.githubusercontent.com/36690888/202018207-4a9670aa-4937-49b7-ae6a-928298900ac0.png">

**Comment by breck7** [comment]
Sorry try running `npm install .; npm run tsc`.
