### ISSUE TITLE
Number of papers referencing Julia is way too low.

### ISSUE THREAD

**Issue by oscardssmith** [breck7/pldb#32]
Google scholar lists 3750 articles citing the main Julia paper (https://scholar.google.com/scholar?cites=12373977815425691465&as_sdt=40000005&sciodt=0,22&hl=en) and semantic scholar shows 38000 papers with Julia as a keyword since 2012, and of the first 10 pages, all appear to be Julia papers.

Also, github shows 14000 repositories with julia code https://github.com/search?q=language%3AJulia&type=Repositories&ref=advsearch&l=Julia&l=. 

I'm also pretty sure the number of downloads is wrong given that https://www.hpcwire.com/2021/01/13/julia-update-adoption-keeps-climbing-is-it-a-python-challenger/ lists 9 million downloads in 2020.

**Comment by breck7** [comment]
Yes, I apologize I just started adding those.

One of my top priorities this week is to improve the papers, books, repo, and file importers.

I think these will be really helpful (when they are actually accurate) :)

**Comment by oscardssmith** [comment]
no problem! This looks like a really good resource, I just wanted to bring it to your attention because I looked at it, and was pretty sure something was up. The 85 jobs also seems really low to me, but I don't actually have any data there.

**Comment by breck7** [comment]
(ah yeah, jobs too) 👍

**Comment by breck7** [comment]
Okay a fix for repo counts is live: https://pldb.com/languages/julia.html

(still working on the other issues)

**Comment by oscardssmith** [comment]
Thanks for fixing these so quickly!

**Comment by oscardssmith** [comment]
Although the number seems to be wrong in the other direction now. The page says 54k, but github says 14k.

**Comment by breck7** [comment]
I saw that discrepancy as well. It shows the number coming from the raw API. I think they provide some filtering on the raw search results (or they just do a partial search). They seem to have that defined as "available repository results":

![Screen Shot 2022-08-29 at 8 03 33 AM](https://user-images.githubusercontent.com/74692/187268222-1bad5eb0-648c-4f41-b19c-90501b0213eb.png)

I think I'm showing the correct number, but maybe the link text could be better so that's not confusing when people follow that link.

**Comment by oscardssmith** [comment]
Also for job numbers, indeed is showing roughly 600 (although I don't know how accurate a count that is). https://www.indeed.com/jobs?q=julia+programming&redirected=1&vjk=5cafb23b1e86ae0c

**Comment by breck7** [comment]
Thanks @oscardssmith ! Okay I am going to clean up the importer code now. I've got someone trying to write a model to better detect false positives (and false negatives) for things like book titles and paper titles. Hopefully that will get up to speed this week and perform well.

**Comment by oscardssmith** [comment]
great! Thanks for all the work on this. It's a really cool resource.

**Comment by Mamolets** [comment]
Hello can I contribute to this issue

**Comment by breck7** [comment]
If anyone wants to work on proper importing of Academic Papers for languages, I'll leave this issue open.

**Comment by breck7** [comment]
Actually I'm going to close this (in keeping with the new convention of closing all issues that are of type "we need to add more data").
