### ISSUE TITLE
database/things/* errata discussion - Part 2 

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#330]
Continuation of Part 1 : https://github.com/breck7/pldb/issues/92

File `database/things/intellect.pldb`  : `Wikipedia link https://en.wikipedia.org/wiki/Intellect` seems to be pointing to unrelated article.

**Comment by adriantintpilver** [comment]
i review the intellect.pldb and i think the description and wikipedia link es correct, but talk about the intellect human and not appear a programing language. i not found anything about a Intellect programing language in internet either. 
Any way its very difficult search this because has so many information about the intellect in different ways, but i don't find nothing about intellect programing language for software and computers.

**Comment by SRS-WRKS** [comment]
@adriantintpilver : Hi thank for the comment. The reference keys value (https://semanticscholar.org/paper/7e2664c73a89b1524313510426ef1b7ca4139828) and hopl keys value (https://hopl.info/showlanguage.prx?exp=761) talk about Intellect by larry harris released in 1970's. wikipedia's disambiguation page  [https://en.wikipedia.org/wiki/Intellect_(disambiguation) ]

does not seem to list this language. I think it should be removed.

**Comment by adriantintpilver** [comment]
i agree with you, there doesn't seem to be a programming language with this name.

**Comment by celtic-coder** [comment]
Issue can now be closed. Thanks, Adrian (@adriantintpilver)!

**Comment by SRS-WRKS** [comment]
@celtic-coder : There are more than 3000 files in pldb. Someone would have contributed time in creating them. Should i open a separate issue for each files content to be deleted/modified ?? I don't feel comfortable deleting file contents without intimation. 

Can i reopen this issue ??

**Comment by celtic-coder** [comment]
I'll reopen. I thought that it applied to this specific set of discrepancies. Sorry about that! 😢

**Comment by SRS-WRKS** [comment]
@celtic-coder : Thank you :)

**Comment by SRS-WRKS** [comment]
Files `database/things/janus-programming-language.pldb` and `database/things/janus.pldb` seem to be duplicates with separate information that points to same thing.

**Comment by adriantintpilver** [comment]
i review the Janus thing, and i see is a triplicated with the janus-lang.pldb too.
i going to merged the three in one with all information.

**Comment by adriantintpilver** [comment]
Deletting tu Janus duplicated (janus.pldb and janus-programing-languaje.pldb)
Keep janus-lang.pldb with marging of all data and update related languaje toontalk.pldb to the good janus-lang link

**Comment by SRS-WRKS** [comment]
Files `database/things/iota-lang.pldb` and `database/things/jot.pldb` seem to be duplicates.

**Comment by adriantintpilver** [comment]
> Files `database/things/iota-lang.pldb` and `database/things/jot.pldb` seem to be duplicates.

i think the real language is "iota and jot" research i found this --> https://en.wikipedia.org/wiki/Iota_and_Jot
right now we have a poor information about jot.pldb and iota-lang.pldb, but i see much information about "iota and jot" language.
What do you think about that?
We also have iota.pldb but this one does sound like something different.

**Comment by SRS-WRKS** [comment]
@adriantintpilver : You are free to delete them, after documenting it here (if you feel the need to) :)

**Comment by SRS-WRKS** [comment]
File `database/things/li-chen-wang.pldb`: file has title Li-Chen Wang which seems to be a persons name. The type is pl (programming language). Wikipedia links to https://en.wikipedia.org/wiki/Li-Chen_Wang who seemed to have a part to play in creation of Palo Alto Tiny BASIC for Intel 8080-based microcomputers.

**Comment by celtic-coder** [comment]
Some other possible programming language duplicates:

- GAMS: [general-algebraic-modeling-system.pldb](https://github.com/breck7/pldb/blob/main/database/things/general-algebraic-modeling-system.pldb) and [gams.pldb](https://github.com/breck7/pldb/blob/main/database/things/gams.pldb). These look to be duplicates. Can they be merged?
- Luna: [luna.pldb](https://github.com/breck7/pldb/blob/main/database/things/luna.pldb) and [luna-1.pldb](https://github.com/breck7/pldb/blob/main/database/things/luna-1.pldb). The first one should be renamed to "enso.pldb" as the language has been renamed and the second one should become the official "luna.pldb".
- Linden Scripting Language: [lsl.pldb](https://github.com/breck7/pldb/blob/main/database/things/lsl.pldb) and [linden-scripting-language.pldb](https://github.com/breck7/pldb/blob/main/database/things/linden-scripting-language.pldb). The second PLDB entry shows that it is related to itself. Could these two entries be merged?
- Q: [q.pldb](https://github.com/breck7/pldb/blob/main/database/things/q.pldb) and [q-equational-programming-language.pldb](https://github.com/breck7/pldb/blob/main/database/things/q-equational-programming-language.pldb). The second entry seems to cover both Q and a language called "Pure". Is there some duplication here?
- Janus: [janus-lang.pldb](https://github.com/breck7/pldb/blob/main/database/things/janus-lang.pldb) and [janus-programming-language.pldb](https://github.com/breck7/pldb/blob/main/database/things/janus-programming-language.pldb). The second one looks incomplete. They are different languages but both have the same title. Perhaps "Janus - Concurrent Constraint Language" for the second title?
- DML: [dependent-ml.pldb](https://github.com/breck7/pldb/blob/main/database/things/dependent-ml.pldb) and [dml.pldb](https://github.com/breck7/pldb/blob/main/database/things/dml.pldb). The second entry seems to be a mixture of many different things. Maybe a cleanup is required?
- Z: [z-expressions.pldb](https://github.com/breck7/pldb/blob/main/database/things/z-expressions.pldb) and [z.pldb](https://github.com/breck7/pldb/blob/main/database/things/z.pldb). These entries have the same list of books, but are different languages. Should the second one be described as a compiler? If so, should the Title be changed?

**Comment by SRS-WRKS** [comment]
File `opl-langage-informatique.pldb` and `database/things/opl.pldb` seem to be duplicates.

**Comment by breck7** [comment]
This is a big issue. Are there things not addressed? If so, can we put them into specific issues?

**Comment by SRS-WRKS** [comment]
@breck7 : There are thousands of entries in PLDB, batching issues could be required to prevent spamming the issues board. 

Your call,  But once i complete the issues that i have started, I plan to list all the files without origin community in PLDB in a single issue. (some origin communities are hard if not impossible to find)

**Comment by breck7** [comment]
> I plan to list all the files without origin community in PLDB in a single issue. (some origin communities are hard if not impossible to find)

@SRS-WRKS this would be great. I think the problem is when we have 1 issue with different kinds of issues (dupes, renames, et cetera).

For small corrections I don't think we need an issue. A commit can be made and if someone things it's a mistake can be reverted. What do you think?

**Comment by SRS-WRKS** [comment]
Ok creating issues. Please dont close this issue, i will do it once i complete some milestones.

**Comment by SRS-WRKS** [comment]
Created issues - 
https://github.com/breck7/pldb/issues/379
https://github.com/breck7/pldb/issues/380


The files mentioned here will be moved to those issues, soon after review.

**Comment by SRS-WRKS** [comment]
closed as pull requests are how errata discussions are handled.
