### ISSUE TITLE
Some enum valued nodes could use definition

### ISSUE THREAD

**Issue by tif-calin** [breck7/pldb#350]
When typing out certain columns we get a nice explanatory comment along with the autocomplete name. This seems to be defined with the `description` attribute in the grammar files

<img width="666" alt="image" src="https://user-images.githubusercontent.com/76538249/204459705-23904e11-d6f3-4e80-9fef-66124165e0ec.png">

With columns such as `type` where we have an enum of possible values, it'd be extremely helpful to have descriptions listed out of all the possible answers since there's soooo many

<img width="397" alt="image" src="https://user-images.githubusercontent.com/76538249/204460339-4e4850fb-d635-4e94-a784-360a88aed43b.png">

What's `plzoo`? 

Another suggestion I'd have specifically for the `type` column (since it's one of the most important) is to have a frequency count on the righthand sidebar. This would make it easy to parse out which values are "niche" or highly specific and which are more common.

I'm not really sure how `jtree` works and haven't had much time to dig into the sourcecode for that but I assume this means these enums would have to be spread out into separate nodes? @breck7 would you know the best way of accomplishing this?

**Comment by SRS-WRKS** [comment]
@tif-calin : Could i add a related issues link to this issue ??

**Comment by breck7** [comment]
This is a great issue and suggestions @tif-calin ! I like the suggestion about frequency count as well. This can be done upstream in JTree/Grammar so CancerDB.com et cetera can benefit too.

**Comment by tif-calin** [comment]
@SRS-WRKS ofc! I can edit the main post too

**Comment by SRS-WRKS** [comment]
@tif-calin : Editing would not be required. I like like cross linking related issues. Thank you and have a wonderful day.

Related issue: https://github.com/breck7/pldb/discussions/130

**Comment by breck7** [comment]
https://github.com/breck7/jtree/issues/182
