### ISSUE TITLE
Download Link for languages / Downlaod page link

### ISSUE THREAD

**Issue by rkimera94** [breck7/pldb#353]
@breck7 @celtic-coder 
I was thinking it would be good to have a link to the official download page or the download  URL  for the languages. Only languages that have a download page and do not need  cloning from Github

**Comment by celtic-coder** [comment]
Yes, Kimera, that would be a useful addition!

**Comment by rkimera94** [comment]
okay, let me work on it @celtic-coder

**Comment by rkimera94** [comment]
@celtic-coder  @breck7  I have raise a PR](https://github.com/breck7/pldb/pull/355)

**Comment by celtic-coder** [comment]
Closed in PR #355
