### ISSUE TITLE
New language request: ccs

### ISSUE THREAD

**Issue by chriscush765** [breck7/pldb#36]
Ccs, a scripting language for infoblox netmri. Here’s a link to official documentation https://www.infoblox.com/wp-content/uploads/infoblox-eval-download-netmri-NetMRI_CCS_Scripting_Guide.pdf

**Comment by breck7** [comment]
Added!

https://github.com/breck7/pldb/commit/2510d91613294c85ead786bea2efcef3909d09d1
https://pldb.com/languages/ccs.html
