### ISSUE TITLE
build.pldb.com - SSL Certificate expired on 7th December

### ISSUE THREAD

**Issue by celtic-coder** [breck7/pldb#365]
Hi Breck (@breck7),

The SSL Certificate [expired](https://www.ssllabs.com/ssltest/analyze.html?d=build.pldb.com&hideResults=on) on the 7th December (4 days ago). Is this a 3-month certificate that has not been automatically renewed?

Kind Regards,
Liam

**Comment by breck7** [comment]
Yikes! I'm surprised I didn't setup autorenew.

That explains a lot of things I've been seeing. Thanks @celtic-coder !

**Comment by breck7** [comment]
Working on it.

**Comment by breck7** [comment]
Should be fixed! I broke the automation of that. Will hopefully get that fixed before March :)

**Comment by celtic-coder** [comment]
Thanks, Breck (@breck7)! Search, among other things, was broken. So, good to have it back!
