### ISSUE TITLE
Broken Wikipedia Links

### ISSUE THREAD

**Issue by celtic-coder** [breck7/pldb#366]
Broken Wikipedia Links

Hi Breck (@breck7),

Many of the Wikipedia links are broken. A link that has text surrounded by underscores is showing `<em>text</em>` in the generated URL.

For example, in [3D Manufacturing Format](https://pldb.com/languages/3mf.html), hovering over the "Read more on Wikipedia..." link shows the following in the status bar:
![3mf-wikipedia-link](https://user-images.githubusercontent.com/11787866/207183827-95c18a70-f56d-4fd9-8a6f-8b3cb2c874dc.png)

The [3mf.pldb #L8](https://github.com/breck7/pldb/blob/main/database/things/3mf.pldb#L8) shows the link as: **wikipedia https://en.wikipedia.org/wiki/3D_Manufacturing_Format**. The underscore in the link is being treated as if it were _emphasis_, as if this were Markdown code, for example.

All the Wikipedia URLs in the languages from https://pldb.com/languages/3mf.html to https://pldb.com/languages/zipper-feature.html are broken in the same manner.

It's not just the Wikipedia links. In the [Symbolic Programming System](https://pldb.com/languages/sps.html) article, for example, hovering over the link next to the "Read more about Symbolic Programming System on the web:" shows the following:

![sps-web-link](https://user-images.githubusercontent.com/11787866/207189491-f389468d-8479-4763-98b0-8f72ac1cf9a9.png)

The [sps.pldb #L4](https://github.com/breck7/pldb/blob/main/database/things/sps.pldb#L4) again shows the underscores in the URL: **reference http://bitsavers.org/pdf/ibm/1620/C26-5600-1_Symbolic_Programming_System_Apr63.pdf**. In this situation, there are two pairs of underscores, so the `<em>text</em>` appears twice.

Might there be some processing of links as if it were Markdown happening in the HTML generation? Or is something else putting the `<em>` text in the links?

Kind Regards,
Liam

**Comment by SRS-WRKS** [comment]
@celtic-coder adds on top of @adriantintpilver 's issue https://github.com/breck7/pldb/issues/340

May be a http link checker could be added to npm run tests ?? 

If node type is urlCell and has http/https link in value, it could be checked automatically ??

**Comment by adriantintpilver** [comment]
It seems to me an excellent idea that it can be checked automatically if the different links are valid and not broken.

**Comment by breck7** [comment]
I think I got all these cases fixed. Going to close. I apologize if I missed any!
