### ISSUE TITLE
Add lang https://github.com/betaveros/noulith

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#367]

**Comment by celtic-coder** [comment]
According to this [Hacker News article](https://news.ycombinator.com/item?id=33980026), the language author was a runner-up in the Advent of Code competition in 2018, and won it in 2019, 2020, 2021, and looks like he can't be beaten in 2022. Writing a new programming language seems to be only one of his many accomplishments!

**Comment by SRS-WRKS** [comment]
I am on it. @celtic-coder Cheering for a champion is always fun :) , now I get back to documenting the winning.
