### ISSUE TITLE
npm run format does not remove trailing white spaces from some subkeys

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#368]
The command `npm run format` does not seem to remove trailing spaces from subkey- value pair(s), while it seems to remove trailing spaces from key-value pairs.

Example is the subkey `summary` for key `wikipedia.`

Trailing spaces stay there even after npm run format command has completed run successfully (according to exit codes)

**Comment by breck7** [comment]
Good point. We could probably do this at the Grammar level, where we forbid empty items in lists.

**Comment by SRS-WRKS** [comment]
I don't know how to edit pldb grammar , I am just starting to try and read up on small grammar changes.

**Comment by breck7** [comment]
I am going to mark this as finished now that we have an easy way to throw error on blank cells.
