### ISSUE TITLE
Trademarks usage in pldb

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#371]
Some open source projects take trademark usage quiet seriously. 

Reference to registered trademarks like Apple instead of Apple,Inc or Microsoft instead of Microsoft Corporation might create issues.

People mistakenly using Free Software Foundation Instead of Free Software Foundation, Inc may be acceptable for some people in certain circumstances though.

Your thoughts ?? May be some one legally knowledgeable could  pitch in too ?? 

An extreme example would be https://en.wikipedia.org/wiki/Mozilla_software_rebranded_by_Debian

**Comment by breck7** [comment]
Great point. We should have better TreeBase tools so we could do global renames so this won't be a problem because we could fix any mistakes instantly in a single commit across the whole database.

**Comment by SRS-WRKS** [comment]
Yes, Batch search and replace, or support for foreign keys both would do the job.

Treebase datatools should be complimentary to ohayo project too

**Comment by breck7** [comment]
I added an easy way to fix these in `code/EditTreeBase.js` (https://github.com/breck7/pldb/commit/64857df5506738587f3cfb88b8e0cda0beedcb30)

We also have some foreign key support in Grammar already but I forget how to use it and it's probably undocumented :(.

High on my todo list!
