### ISSUE TITLE
add lang https://docs.racket-lang.org/video@video/index.html

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#373]

**Comment by SRS-WRKS** [comment]
I am on it.

**Comment by SRS-WRKS** [comment]
It looks like video was already added, i am just enhancing an already existing entry (added in commit 273f34a8620111e326a49332761e2c01823b58ef )

**Comment by SRS-WRKS** [comment]
Please see https://github.com/breck7/pldb/commit/6c08ec0721fd713580ffa5ae9fffd92682ca2593
