### ISSUE TITLE
Add lang: incopy markup language

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#377]

**Comment by vishisht08** [comment]
Hey i would like to work on this issue can u please assign me with this one @breck7

**Comment by breck7** [comment]
No need to assign it. Just go ahead and get it done @vishisht08!

**Comment by vishisht08** [comment]
Where can I get the code of this particular issue @breck7

**Comment by breck7** [comment]
No code is needed @vishisht08. You can solve this issue just by using this form: https://build.pldb.com/create

**Comment by breck7** [comment]
I added it https://github.com/breck7/pldb/commit/555f62fe4d45a382eb3a79ff7198e172c58e2623
