### ISSUE TITLE
Add a way to suggest removing languages?

### ISSUE THREAD

**Issue by Timmmm** [breck7/pldb#381]
E.g. the database includes Deno which is not a programming language. I like your "improve this page" feature but it doesn't have a way to suggest deletion.

**Comment by Timmmm** [comment]
Arduino is another one. I guess these were scraped from Wikipedia or something?

**Comment by breck7** [comment]
For Arduino our page is about the "Arduino Programming Language" which is mostly C++ but a little different. I've added a line `extensionOf cpp`. In general, we don't do a good job yet of showing the sometimes intricate relationships between languages.

Arduino is popular enough that a lot of people might be quite good with Arduino but bad with C++ or vice versa so I think it deserves it's own page. We should do a better job of explaining those nuances though.

As for Deno, this one comes up a lot. It still seems to be evolving at a rapid pace and I don't know where it will end up. Is it a superset of TypeScript? I know there are some subtle differences between in the Deno experience (that may have been ironed out by now, I'm not too familiar) that would warrant it being called it's own language (but we should have the correct extension of or fork of or subset/superset relationships), and not just a runtime.

I am not an expert on that one but would be open to pull requests.

Removing a language is easy — just send a pull request with the file deleted.

**Comment by Timmmm** [comment]
> our page is about the "Arduino Programming Language" which is mostly C++ but a little different

I don't think it is? It's 100% C++. Not sure why they call it the "Arduino Programming Language". Maybe "Arduino C++ API" is too much for beginners.

> Is it a superset of TypeScript?

No, it's literally just TypeScript. I think the only very slight difference is that you can `import ... from "foo.ts"` whereas in Typescript you'd do `import ... from "foo"` or `import ... from "foo.js"` but that's a minor file naming issue. It doesn't make it a new language.

I think if you really want to keep them I would add a `platform` category instead which could be used for e.g. Node, V8, Pypy, LuaJIT, Arduino, Processing, etc.

**Comment by breck7** [comment]
> I don't think it is? It's 100% C++. Not sure why they call it the "Arduino Programming Language". Maybe "Arduino C++ API" is too much for beginners.

I think the general problem is we need to have more data on compilers. It seems like Arduino uses the `AVR-GCC` compiler, which we don't yet have a page on. I don't have enough experience with Arduino to make a ruling either way. I think even if it's 99% C++, but there are certain flags or nuances that make it separate, it has a big enough following that it might warrant it's own page. I think another general problem is we don't do a good enough job of getting folks from their communities actively involved in keeping their pages up to date. A big part of the reason for this is the TreeBaseServer editing experience is still so poor. That's my fault. Once that is better, and adding data is a lot more pleasant, I think we can start recruiting more contributors and iron out all these subtle things.

> No, it's literally just TypeScript. I think the only very slight difference is that you can import ... from "foo.ts" whereas in Typescript you'd do import ... from "foo" or import ... from "foo.js" but that's a minor file naming issue. It doesn't make it a new language.

If someone creates a fork of Javascript except without the `var` keyword, and calls it `BubbleScript`, then we won't add it as a language...UNLESS it suddenly gets something like 100,000 users. Deno I suspect will increasingly become its own language as it evolves.

**Comment by breck7** [comment]
I'm going to close this for now, since we will keep Deno and Arduino pages but always open to Pull Requests with taxonomy improvements!
