### ISSUE TITLE
Add column for whether a language supports conditional expressions, like kotlin

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#386]

**Comment by rkimera94** [comment]
@breck7  I have seen the comment,   should it be like pseudocode?  Trying to think of a way how to implement it. 

<img width="536" alt="Screenshot 2023-01-19 at 19 36 44" src="https://user-images.githubusercontent.com/54355787/213500498-0802395d-2c20-4378-8baa-3d6f0d1017df.png">

**Comment by breck7** [comment]
Hi @rkimera94, Kotlin's example is good: https://kotlinlang.org/docs/control-flow.html#if-expression

```
val max = if (a > b) a else b
```

The key thing is to emphasize that some languages have `if` expressions that work like the `ternary` operator. I'm curious how common this is.

**Comment by breck7** [comment]
closing for now
