### ISSUE TITLE
What exactly is a features keywords set ?

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#394]
pldb has a set of keys called features (I think).

Going though pull request https://github.com/breck7/pldb/pull/387

How exactly is it different from computed columns or simply a normal key ?
It was supposed to be mentioned in 2 places: a grammar entry as well as a feature file in the database.

Where is a feature file in the database ?

**Comment by breck7** [comment]
> How exactly is it different from computed columns or simply a normal key ?

Features are now just normal keys.

> It was supposed to be mentioned in 2 places: a grammar entry as well as a feature file in the database. Where is a feature file in the database ?

I removed this. It was a bad design. Now features are just normal keys, just like any others.

For example, here is the entire code for `hasLineComments`:

https://github.com/breck7/pldb/blob/main/database/grammar/hasLineComments.grammar

**Comment by SRS-WRKS** [comment]
Jan 19, 2023, 21:57 by ***@***.***:

>
>
>
>
>>
>> How exactly is it different from computed columns or simply a normal key ?
>>
>>
>
> Features are now just normal keys.
>
>
Thank you for the reply. But what was it before ??

May be i should have asked "How exactly was it different from computed columns or simply a normal key ?"

 I am just documenting the types of keys that pldb supports, please help :)

**Comment by breck7** [comment]
> But what was it before ??

A bad complicated design! Not worth documenting. The way I implemented it was a mistake. The lesson learned was: keep it simple. 1 folder/1 treebase = 1 table.

**Comment by SRS-WRKS** [comment]
Thank you.
