### ISSUE TITLE
Should we support FTP links?

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#396]
We only have 2:

```
reference ftp://ftp.software.ibm.com/software/rational/docs/documentation/manuals/v2001a/Rational_Test/sqabasic.pdf

reference ftp://gcc.gnu.org/pub/gcc/summit/2003/GENERIC%20and%20GIMPLE.pdf
```

My thought is no since if we only have 2 at this point then not worth the hassle. But not sure if anyone has a good reason to support those?

**Comment by breck7** [comment]
If we do support them, I have to add support for them in Scroll.

**Comment by SRS-WRKS** [comment]
Should scroll support single prort links or multi port links is the bigger question.

A unix puritan who likes blank lines at the end of the files, supporting a single port protocol links, like a modern GUI browser (firefox, chromium,etc)

Do you really want to follow the unix trend, when you want to build a custom build system :) 

Aargh

**Comment by breck7** [comment]
Not a big deal. Closing for now
