### ISSUE TITLE
Hard coded year values

### ISSUE THREAD

**Issue by celtic-coder** [breck7/pldb#402]
Hi Breck (@breck7),

On the [About](https://pldb.com/pages/about.html) page in the **Citation** section, the year is hardcoded:

![citation-year](https://user-images.githubusercontent.com/11787866/215499064-b7c96237-f6f9-4b8c-8fc1-0a5084bc429e.png)

Perhaps, something like `replaceJs` (as in line [#32 of about.scroll](https://github.com/breck7/pldb/blob/main/site/pages/about.scroll#L32)) could be used for the year:

![replaceJs-example](https://user-images.githubusercontent.com/11787866/215500434-d5a4f90c-d628-44e0-9b26-f95fd90d8a7d.png)

Just use a variable like CURRENT_YEAR with the appropriate JavaScript code?

The **Citation** section also appears in the main Readme Scroll ([lines 58-71](https://github.com/breck7/pldb/blob/main/readme.scroll#L58-L71)):

![citation-in-main-readme](https://user-images.githubusercontent.com/11787866/215503224-36cb82cf-ca48-4eb4-aff9-0cbf6f6f3ecf.png)

Could this be moved out into a separate file and then use `import` wherever it is required?

The one other place that I noticed a hard coded year value is in [line 35 of Awis.ts](https://github.com/breck7/pldb/blob/main/code/crawlers/awis/Awis.ts#L35) crawler:

![const-year-in-awis-ts](https://user-images.githubusercontent.com/11787866/215543996-0f624168-63d7-4ef9-b6b9-c668175840bf.png)

Again, could this possibly be replaced by some global variable or does it need to be year specific?

Kind Regards,
Liam

**Comment by breck7** [comment]
Hi @celtic-coder ! That's a good point. I was thinking that someone would cite the first year something came out, but you are right it makes more sense to cite the year it was accessed since it is continually updated.

I would accept a pull request on this.
