### ISSUE TITLE
add lang

### ISSUE THREAD

**Issue by hassamalhajaji** [breck7/pldb#403]
Links
https://www.hecl.org/
https://github.com/davidw/hecl/

**Comment by hassamalhajaji** [comment]
What's missing here? 59ada5f @breck7

**Comment by breck7** [comment]
@hassamalhajaji `type`

**Comment by breck7** [comment]
There should be a better error message for that. I'm gonna do a big cleanup of the editor.

**Comment by hassamalhajaji** [comment]
Thank you. I'll keep note of that!
