### ISSUE TITLE
Should pldb support a list creation UI

### ISSUE THREAD

**Issue by ghost** [breck7/pldb#407]
I cant seem to understand how to create my own lists in pldb (preferably locally check out only with remote commit/push being optional)

That way some work can be handed over as lists to contributors and tracking progress before committing would be easier.

**Comment by breck7** [comment]
Yes! This is a great way to describe it @SRS-WRKS. Previously lists were generated by hard coded TypeScript functions. Now anyone can generate them using TQL. We will probably always have a few static list pages (calendar, for example). Certain pages like "Creators" and "Features" will be generated statically as well (though maybe we'll add more advanced keywords like `groupBy` to TQL in the future and could even make those pages the results of a TQL query).

To make it even clearer that people can make their own lists now, I just added the `title` and `description` keywords to TQL, so you can make nice looking list pages. For example:

https://build.pldb.com/search?q=where+appeared+%3E+2009%0D%0Awhere+appeared+%3C+2020%0D%0AnotMissing+githubRepo.stars%0D%0AsortBy+githubRepo.stars%0D%0Aselect+appeared+githubRepo.stars+type%0D%0Atitle+Top+100+languages+and+frameworks+created+in+the+2010%27s+on+GitHub+by+stars%0D%0Alimit+100%0D%0Areverse

**Comment by breck7** [comment]
Other features in TQL that would make it easier to create lists @SRS-WRKS ?

**Comment by SRS-WRKS** [comment]
Shareable links for lists, the ability to load TQL scripts into web UI. People can either load the script script from their storage (like a storage bucket) or a share link


Sharable links like `https://build.pldb.com/search?q=where+appeared+%3E+2009%0D%0Awhere+appeared+%3C+2020%0D%0AnotMissing+githubRepo.stars%0D%0AsortBy+githubRepo.stars%0D%0Aselect+appeared+githubRepo.stars+type%0D%0Atitle+Top+100+languages+and+frameworks+created+in+the+2010%27s+on+GitHub+by+stars%0D%0Alimit+100%0D%0Areverse`
already exist :) 


Your thoughts ?

**Comment by breck7** [comment]
We have this now. For example, here are the top languages from the 1970's:

https://pldb.io/lists/explorer.html#searchBuilder=%7B%22criteria%22%3A%5B%7B%22condition%22%3A%22%3E%3D%22%2C%22data%22%3A%22appeared%22%2C%22origData%22%3A%22appeared%22%2C%22type%22%3A%22num%22%2C%22value%22%3A%5B%221970%22%5D%7D%2C%7B%22condition%22%3A%22%3C%22%2C%22data%22%3A%22appeared%22%2C%22origData%22%3A%22appeared%22%2C%22type%22%3A%22num%22%2C%22value%22%3A%5B%221980%22%5D%7D%2C%7B%22condition%22%3A%22%3C%22%2C%22data%22%3A%22rank%22%2C%22origData%22%3A%22rank%22%2C%22type%22%3A%22num%22%2C%22value%22%3A%5B%22100%22%5D%7D%5D%2C%22logic%22%3A%22AND%22%7D
