### ISSUE TITLE
GitHub repository count from BigQuery is inaccurate, easy fix with GitHub's API

### ISSUE THREAD

**Issue by Yardanico** [breck7/pldb#41]
Hello, just saw your project on HN and it looks very interesting :) One thing I immediately noticed is that pldb seems to be using bigquery github data to show repository count of different languages. Sadly that bigquery dataset seems to be quite limited, and there's a much better way to find the number of repositories written in a specific language:

```sh
# Use per_page=1 so that we don't waste much bandwidth
$ curl "https://api.github.com/search/repositories?q=language:nim&per_page=1"
{
  "total_count": 8013,
  "incomplete_results": false,
  "items": [
    {
     <omitted for readability purposes>
    }
  ]
}
```

The actual count is in the `total_count` field, and it's only unique repositories (it doesn't count forks). If you want to also count forks (but I don't think it'd be a good idea) you can do
```sh
$ curl "https://api.github.com/search/repositories?q=language:nim+fork:true&per_page=1"
{
  "total_count": 18320,
  "incomplete_results": false,
  "items": [
    {
     <omitted for readability purposes>
    }
  ]
}
```

I don't know if these results are 100% exact, but they seem to be much more real than the BigQuery count.

**Comment by Yardanico** [comment]
FYI, docs for REST API for search is on https://api.github.com/search/repositories

**Comment by Yardanico** [comment]
Also, sorry for an unrelated questions, but does pldb only accept English books to add to the language page, or books in other languages are also accepted?

**Comment by breck7** [comment]
Thanks for the very helpful report @Yardanico! I am aware of this and my plan at the moment is to add those counts asap (hoping tomorrow, we'll see).

On the question of books, do you have an ISBN number? If so should be no problem. I should probably add a general "books" keyword, as I think right now all the books are coming from ISBNdb and/or GoodReads. Can probably add that on Monday too.

**Comment by breck7** [comment]
Very helpful report. You made it a lot easier to get this fixed. Thanks @Yardanico ! When you have a chance to review, you could take a look at https://pldb.com/languages/nim.html?
