### ISSUE TITLE
Add/Edit language bug bash

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#410]
Now that a lot of the technical debt has been cleaned up, let's make it faster to add a language and edit languages.

**Comment by breck7** [comment]
Permalink cells should have autocomplete and error checking

**Comment by breck7** [comment]
`example` nodes should have some better coloring.

**Comment by breck7** [comment]
It just took 26 seconds to save a language. Terrible!

**Comment by breck7** [comment]
We should probably have a `format` button.

**Comment by breck7** [comment]
Missing `type` still allows people to submit.

**Comment by breck7** [comment]
Casing is an issue. I just added "TQL" and the permalink is all uppercase.

**Comment by breck7** [comment]
As soon as you update a language the site should update

**Comment by breck7** [comment]
It is time to ditch the 2 servers and make the dynamic site the primary and static site the secondary

**Comment by SRS-WRKS** [comment]
> We should probably disable the submit button if there are errors.


I still haven't found a way to add a single pldb treebase file and run all the tests without rebuilding the entire project.


It would be useful for both web based contributors and command line contributors.

**Comment by breck7** [comment]
I think this one will cover the remaining items:

https://github.com/breck7/pldb/issues/451
