### ISSUE TITLE
404 in URL at /languages/java.html

### ISSUE THREAD

**Issue by stavares843** [breck7/pldb#411]
STR:
- go to https://pldb.com/languages/java.html
- search by ''pygments'' keyword in the page
<img width="322" alt="Captura de ecrã 2023-02-01, às 19 46 49" src="https://user-images.githubusercontent.com/29093946/216147462-20cbc863-d5b3-437d-b459-d4610b0187f6.png">
- click in that pygments url
- goes to https://pldb.com/languages/languages/pygments.html and returns 404

<img width="1207" alt="Captura de ecrã 2023-02-01, às 19 47 34" src="https://user-images.githubusercontent.com/29093946/216147644-21f907b8-8270-4740-84bf-b422162f6619.png">

**Comment by breck7** [comment]
Thanks @stavares843 !!
