### ISSUE TITLE
404 at URL in posts/index.html

### ISSUE THREAD

**Issue by stavares843** [breck7/pldb#412]
STR:
- Go to https://pldb.com/posts/index.html
- Search in the page by "5.3"
<img width="286" alt="Captura de ecrã 2023-02-01, às 19 50 09" src="https://user-images.githubusercontent.com/29093946/216148181-7012823a-12dc-4f86-8870-dd5fdb3758c8.png">

- Click on that 5.3 link
- Goes to https://www.linkedin.com/topic/javascript and returns 404 logged in or not in LinkedIn

<img width="1164" alt="Captura de ecrã 2023-02-01, às 19 50 41" src="https://user-images.githubusercontent.com/29093946/216148299-5ddbd64d-adfa-4c1e-868a-6a22a2428653.png">

**Comment by stavares843** [comment]
seems that topics were ditched from LinkedIn we can either update the URL or remove that hyperlink, suggestions? 🔨

**Comment by breck7** [comment]
Great work @stavares843! Does LinkedIn have anything similar we can use now instead?

**Comment by stavares843** [comment]
Not that I could find, I noticed they have a posts section but that includes everything from job posts to other posts.

**Comment by breck7** [comment]
We can fix linked in/jobs stuff eventually. Not an urgent priority for me now, but if someone wants to send a PR with a good idea thatd be nice.
