### ISSUE TITLE
404 at title in /create

### ISSUE THREAD

**Issue by stavares843** [breck7/pldb#421]
STR:
- go to https://pldb.com/create
- click on ''add a language'' title

<img width="988" alt="Captura de ecrã 2023-02-03, às 17 15 50" src="https://user-images.githubusercontent.com/29093946/216665883-3018c50f-038a-4e12-a25a-bb09ac105b9d.png">

goes to https://pldb.com/.html and returns 404

**Comment by stavares843** [comment]
should that title be not clickable?

**Comment by breck7** [comment]
Good find @stavares843 !

That is a bug in Scroll.

Simple repro:
https://try.scroll.pub/#scroll%0A%20title%20Add%20a%20language

The `title` design is bad. I'll create an issue on Scroll repo.
