### ISSUE TITLE
404's in footer in main page

### ISSUE THREAD

**Issue by stavares843** [breck7/pldb#422]
STR:
- go to https://pldb.com/
- in the footer, both https://pldb.com/trafficToday.html and https://pldb.com/trafficTrends.html returns 404

<img width="195" alt="Captura de ecrã 2023-02-03, às 17 18 28" src="https://user-images.githubusercontent.com/29093946/216666293-8babf79e-f779-4a44-afc4-7945729b5e0b.png">

**Comment by breck7** [comment]
These are fixed now.

PLDB started as a static jekyll blog on 1 server. Then I added the express app on a 2nd server so we could have search and web editing.

Today I retired the static server and now we just have 1 server again, except this time dynamic.

I did not port over the old stats so it will take time for those pages to have data again.

**Comment by stavares843** [comment]
thanks! 🔨
