### ISSUE TITLE
Missing file - homepageImports.scroll

### ISSUE THREAD

**Issue by stavares843** [breck7/pldb#425]
STR:
- when running the tests using `npm run test` returns error

<img width="685" alt="Captura de ecrã 2023-02-03, às 19 28 11" src="https://user-images.githubusercontent.com/29093946/216690704-3c326819-bcc4-4d93-9350-c44ea8247242.png">

but seems that file doesn't exist

<img width="331" alt="Captura de ecrã 2023-02-03, às 19 27 43" src="https://user-images.githubusercontent.com/29093946/216690823-2570d1b7-3c55-4e48-aa22-b1c0b6993e81.png">

i also noticed 2 other files importing that file

<img width="763" alt="Captura de ecrã 2023-02-03, às 19 27 51" src="https://user-images.githubusercontent.com/29093946/216690886-d5cb07db-e1e3-4560-9560-7d959cf47c37.png">

**Comment by breck7** [comment]
Sorry! You have to run `npm run build` first.

**Comment by stavares843** [comment]
worked now! thought only `npm i `was needed for the `npm run test`, thanks! 🔨

**Comment by breck7** [comment]
I'm currently rewriting the build code and ideally will get rid of that step

**Comment by SRS-WRKS** [comment]
@breck7 @stavares843 : Possibly related https://github.com/breck7/jtree/issues/172
