### ISSUE TITLE
Delete SiteBuilder.ts

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#432]
Now that we are a dynamic site and not static, SiteBuilder.ts can be refactored out simplifying a lot.

**Comment by SRS-WRKS** [comment]
dynamic scroll HOWTO would be nice to document :)

**Comment by breck7** [comment]
SiteBuilder.ts is gone! Still a little bit of a build step but much better.

@tomdseo any luck on Scroll docs? If you get those live I can add a section on using Scroll in dynamic sites to answer @SRS-WRKS 's request.
