### ISSUE TITLE
year column populated with month and day 

### ISSUE THREAD

**Issue by stavares843** [breck7/pldb#457]
STR:
- go to https://pldb.com/languages/java.html
- the year column some of the date also includes day and month and some appears like this

<img width="1092" alt="Captura de ecrã 2023-02-09, às 16 57 44" src="https://user-images.githubusercontent.com/29093946/217884424-ba081b8b-2432-4f51-8470-fafbb6d89ffd.png">

**Comment by stavares843** [comment]
should we clean up the data to display just the year instead? cc @breck7

**Comment by breck7** [comment]
The book data was from a crawl that was not good enough, so I removed for now.

In the future we can add back better
