### ISSUE TITLE
ERR_ADDRESS_UNREACHABLE at /docs/csv.html

### ISSUE THREAD

**Issue by stavares843** [breck7/pldb#459]
STR:
- go to https://pldb.com/docs/csv.html
- click on antlr.org

<img width="952" alt="Captura de ecrã 2023-02-09, às 17 07 43" src="https://user-images.githubusercontent.com/29093946/217886577-b4f85105-4f0c-40e9-a8aa-eb61d72a4910.png">

returns error

<img width="1039" alt="Captura de ecrã 2023-02-09, às 17 08 00" src="https://user-images.githubusercontent.com/29093946/217886638-f3b469d4-be15-43ea-8ff3-3744f3b8f78b.png">

**Comment by stavares843** [comment]
does it open for anyone? let me know if i should remove it 🔨

**Comment by celtic-coder** [comment]
Hi Hari (@SRS-WRKS),

http://antlr.org automatically [redirects](https://wheregoes.com/trace/2023643395/) to https://www.antlr.org/ without the need for the leading "www" on the non-SSL version. Therefore, the non-SSL version can be used in the link in the PLDB and it will work fine.

Kind Regards,
Liam

**Comment by stavares843** [comment]
will update 🔨
