### ISSUE TITLE
404 in /languages/c.html

### ISSUE THREAD

**Issue by stavares843** [breck7/pldb#460]
STR:
- go to https://pldb.com/languages/c.html
- click in Read more about C on the web: [1.](http://www.c4learn.com/c-programming/c-keywords/)

<img width="272" alt="Captura de ecrã 2023-02-09, às 17 19 18" src="https://user-images.githubusercontent.com/29093946/217889372-299c7dcf-e177-4ad7-87df-e9edfbb2bdb7.png">

- goes to http://www.c4learn.com/c-programming/c-keywords/ and returns 404

<img width="808" alt="Captura de ecrã 2023-02-09, às 17 19 10" src="https://user-images.githubusercontent.com/29093946/217889329-3f449f58-4864-4a39-89bf-92f24635e14e.png">

**Comment by SRS-WRKS** [comment]
@stavares843 : Possibly related https://github.com/breck7/jtree/issues/172

**Comment by breck7** [comment]
Should be fixed
