### ISSUE TITLE
404 in /languages/ruby.html

### ISSUE THREAD

**Issue by stavares843** [breck7/pldb#463]
STR:
- go to https://pldb.com/languages/ruby.html
- click in the implementation url

Ruby [LSP](https://pldb.com/languages/language-server-protocol.html) [implementation](https://github.com/kwerle/ruby%3Cem%3Elanguage%3C/em%3Eserver)

<img width="212" alt="Captura de ecrã 2023-02-09, às 17 57 20" src="https://user-images.githubusercontent.com/29093946/217898066-aae9b724-638c-49b8-ab05-29bbcb115a2b.png">

goes to https://github.com/kwerle/ruby%3Cem%3Elanguage%3C/em%3Eserver and returns 404

**Comment by SRS-WRKS** [comment]
@stavares843 :
Thank you for the issue. pldb testing does not check URL's for a lot of things (except may be URL format i think).
you could ask @breck7 to consider selenium/webdirver testing integration or may be just command like Url node checking using curl as part of test suit upgrade :)

**Comment by breck7** [comment]
Would accept a pull request to fix.
