### ISSUE TITLE
License Missing

### ISSUE THREAD

**Issue by tderflinger** [breck7/pldb#48]
Hi there,

fantastic project with lots of useful information on programming languages! 

One suggestion for the GitHub repository. Please add a LICENSE file, then the License information is visible on the right.

Thanks!
-Thomas

**Comment by breck7** [comment]
I know that's intentional.

It's all public domain.

I don't believe in the concept of licenses. (I know I'm weird ;) ).

I do love MIT and GPL et cetera, but I hope we can move to a more intellectually free world and put the idea of "licenses" on ideas to rest.

**Comment by WickedSmoke** [comment]
Copyright is the law of the land on most of planet Earth, so your repository data is NOT in the public domain unless it is declared as such.  The license file is the perfect place to make this declaration and make your wishes known to users of the data.  Note that many projects name this file "COPYING" rather than "LICENSE", so Github also looks for that.

**Comment by breck7** [comment]
I think these are fair points. I'm going to reach out to an expert I know in this field and she if she can weight in.

**Comment by breck7** [comment]
OK THE WORLD'S FOREMOST EXPERT ON THIS TOPIC HAS SPOKEN AND SHE HAS SAID: "Note that raw “data” – facts, information, and such – is not copyrightable so that stuff is born public domain.".

THANK YOU @tderflinger AND @WickedSmoke FOR FORCING US TO GET TO THE BOTTOM OF THIS ISSUE.

**Comment by WickedSmoke** [comment]
The larger body of work is subject to copyright law unless you explicitly waive your rights.  You can read about this from numerous sources such as

https://sco.library.emory.edu/research-data-management/publishing/copyright-data.html

The key take away from that page is:

>  Leaving your dataset unlicensed creates uncertainty about the use and re-use of your data. Licensing your data explicitly states that your data is open for re-use.

All I'm asking for is a file in the root directory that will remove the uncertainty.
