### ISSUE TITLE
list of all the languages

### ISSUE THREAD

**Issue by hassamalhajaji** [breck7/pldb#485]
If we go to https://pldb.com/lists/top1000.html and click the link to view "all the languages" it sends us to https://pldb.com/truebase/search.html

The top1000.scroll file has search query that might not be executing properly.

link BASE_URL/search?q=select+type+appeared all the languages

**Comment by breck7** [comment]
Nice catch! Should be fixed here: https://github.com/breck7/pldb/commit/e7a75d55f4d33e7caa006fee6b2cedce09b55221
