### ISSUE TITLE
Shakespeare language duplicate

### ISSUE THREAD

**Issue by nmkolp** [breck7/pldb#486]
https://github.com/breck7/pldb/blob/main/truebase/things/shakespeare-programming-language.pldb

is a duplicate of

https://github.com/breck7/pldb/blob/main/truebase/things/shakespeare.pldb

**Comment by celtic-coder** [comment]
Hi @nmkolp,

Yes, these are indeed duplicates. I will take care of this in the coming days.

Kind Regards,
Liam

**Comment by breck7** [comment]
looks like this was fixed
