### ISSUE TITLE
keys with multi value sets and their operators

### ISSUE THREAD

**Issue by ghost** [breck7/pldb#487]
Lets talk about a common key with multi-value set as value, like country.

Two operators exist, and AND or currently.

I don't know enough about true base to know if logical operations are possible for the values (logical OR is different from or used in spoken language) or if there are plans to allow the same (set theory is beyond my limited skill-set). 

Does the developers feel the need to add something like Alias to the set of operators (shorthand is ==)
So if a language in pldb was developed in former east Germany and the date of editing it was in 2023 this could be written as follows:
`tile FOO-language `
`country Former East Germany == Germany`

**Comment by breck7** [comment]
I will add this at the Scroll level https://github.com/breck7/scroll/issues/113
