### ISSUE TITLE
missing License files

### ISSUE THREAD

**Issue by hgkamath** [breck7/pldb#503]
Please include the LICENSE files in the top level folder to inform potential contributors

I guess you need a license file each for both the
1. the scroll based site-generator input-content [link](https://github.com/breck7/scroll)
2. the actual data that constitutes the entries in the PLDB, which are metadata about various programing-languages.

Firstly, thank-you to the developers for their efforts towards this interesting/informative project.

Personally, I am hoping that it is liberal open-source and liberal open-data.

[Edit] sorry for dup , I just happened to search in closed issues. Found the following
- https://github.com/breck7/pldb/issues/48
- https://github.com/breck7/scroll/issues/106 
- https://github.com/breck7/CancerDB/issues/7

.
- Since you yourself (in addition to manual work.) glean/crawl/scrape from wikipedia and other independent sources, it is understandable that you think it not necessary. 
- The risk to contributors is that the their contribution to a project may one day become proprietary.  
- It induces a wrong way to induce newbie contributors to contribute. Even if you/this-project comes clean on words to keep open, a newbie contributor who like-wise habituates to always doing so to other projects will one day learn the hard way. I think a general warning to all contributors is beware of vague licenses (like stay away from drugs slogan), and all who want to encourage a world with contribution/sharing type projects encourage all to discern. 
- I am not opposed to proprietary crowd sourced work, it just that if contributors spend their time doing so, let them do so knowing-fully. Personally, I use them if freely accessible, let the ads make them revenue.
- wickedsmoke has already [commented](https://github.com/breck7/pldb/issues/48#issuecomment-1245851236) that law of most lands is to protect creators-ownership by default for. Unless the creator explicitly waives it off. Furthermore not having a license is just introducing fear/uncertainty.
- Copyright law is only a temporary unnatural law that last usually 117 years, with the intention to benefit creator, after which said content becomes public domain. So as to reward the creator who worked to create that content. Protection-first is the default as opposed to free-first, because the norm, more often than not, is that people who worked to create something want protection and there is danger if the default were the other way round. Open/free software is exception to the norm, wherein the goal is incentivize participation and contribution, by fostering a strong feeling of 'cooperation', but which requires giving up absolute ownership and control. 
- > OK THE WORLD'S FOREMOST EXPERT ON THIS TOPIC HAS SPOKEN AND SHE HAS SAID: "Note that raw “data” – facts, information, and such – is not copyrightable so that stuff is born public domain.". [link](https://github.com/breck7/pldb/issues/48#issuecomment-1243161844)
  
  Maybe true, but doesn't hurt to be explicit even if redundant. Perhaps one could additionally include in the license the statement that data is already free-beer/free-speech/open/public , so as to reinforce the freeness.
  This person seems known to you. Expertise is reputation based subjective evaluation. Even if an expert says so, it does not seem worth the risk. 
  That said there is structure and file-format which is work and has a derivative value.   
  While the facts themselves are free, the format/manuscript are entities in themself. Its not like one is manually transcribing only the facts.  
  I wonder about things like lib.reviews, [freedb](https://en.wikipedia.org/wiki/Freedb) (libre) vs imdb,, cddb (proprietary)  
  But, where does it end? How about contributions to Q&A sites like quora?
  Whom do crowd sourced contributions belong to?  
  There are many cases like the following case: bacula vs bareos backup software. Bareos forked from Bacula because the Bacula founder also had a commercial edition and there were suspicions whether contributions made it to free opensource community product.
  A contributor agreement may placate an obvious concern. It may also be true, in the event of a legal wrangling sometimes free rights remains, but who wants all that court hassle. 
- Often, a contribution is not fact copy, and not always easily deducible-able. It may have required the contributor to apply original or own thinking to apply concepts and make a deduction about a property.  Ex: (made up maybe trivial) Like is GW-BASIC a dynamic type language and the answer-fact is not be explicitly stated on the wiki-page for it.
- How would you react if someone were to fork your repo and do their own thing? Would it bother you if it became an alternative public/private or open/non-open variant with incompatible modifications?
- What if, let's  hope not, something happens to you? would happens to the digital assets and would the next custodian keep the same open/free views? If that person does not, that would be a very valid reason to fork. 
- > Besides this, are there any other things that we could improve to make Scroll better serve you? [link](https://github.com/breck7/scroll/issues/106#issuecomment-1533851736)
  > > No response from @penyuan so closing this one. [link](https://github.com/breck7/scroll/issues/106#issuecomment-1571142508)
  
  When you ask a question like that, its not surprising that the OP, who seems like an active github contributor, did not answer. Usually the answer could be yes. But they may hesitate to be forthcoming 
  The absence of contributor agreement might be decreasing crowd participation and potential contributors may abstain,

It doesn't have to be a LICENSE.txt with a gazillion legalese lines, per say.  
It could also be a COPYING document, a CONTRIBUTOR_AGREEMENT.txt, FAQ.txt or even a README.txt , wherein in brief text in simple English parlance you assure openness/freeness of all files in the git-repo, as well as the reasons/opinion on nature of IP on facts etc.  (in the same manner as how you have already commented). Instead of having to search and find in closed issues in the bug-tracker. The declaration is up front and center.  It will at-least avoid a repeat filing of a bug by a next person, saving time for both.  

I may not be able to add to the discussion.   
My guess is you have some stand about this.  
Feel free to close the issue if your mind is made up.

**Comment by SRS-WRKS** [comment]
Hey @hgkamath :
 You seem to have posted a very detailed and thorough issue. @breck7 Seems to be busy/hard to reach as of today, will probably get back to you soon !!.


Please note @breck7 is very serious about software licenses. As far as  i know, he has put in a lot of effort,  to respect the license of (https://hopl.info/home.prx) and some other projects.. I am not qualified to talk about the rest of the points in the issue.

**Comment by breck7** [comment]
Thank you for the well thought out issue @hgkamath.

>  It will at-least avoid a repeat filing of a bug by a next person, saving time for both.

This is something I can agree with. I don't want to waste anyone's time.

> It could also be a COPYING document, a CONTRIBUTOR_AGREEMENT.txt, FAQ.txt or even a README.txt 

The current readme file mentions that this is public domain twice, including in the very first sentence "PLDB is a public domain database and website containing over 135,000 facts about over 4,000 programming languages." However, I understand what you are saying, that we don't have it in a conventional place.

Is there a way on GitHub/NPM/etc where we can indicate that this is public domain without resorting to using the word "license"?

I cannot for the life of me think of a morally valid argument that supports having copyright law or licenses on ideas. Here is my model on the topic: https://breckyunits.com/a-mathematical-model-of-copyright.html

I think the issues you raise are all very valid, and show how complex it is to add such an unnatural system. I think the proper response is to bring awareness to this and take a clear stance, based on first principles, that we should not have a concept of licenses on ideas.

I am open to counter arguments. I am also open to ways to promote this position while not wasting anyone's time.

That's certainly not something I want to do!

Thanks for your help thinking through this issue.

**Comment by hgkamath** [comment]
> Is there a way on GitHub/NPM/etc where we can indicate that this is public domain without resorting to using the word "license"? 

penning for completeness. I'm sure you've seen this as well.  
I did not know the answer at the time, and even now still don't for sure, hence had not replied. 
I kept it in the back burner in my mind, and as I've browsed. I've seen the following in use. They mostly have the same assurances and disclaimers of the MIT license 
-  "the unlicense" license ([wiki](https://en.wikipedia.org/wiki/Unlicense), [web](https://unlicense.org/), [fsf](https://www.gnu.org/licenses/license-list.en.html#Unlicense) )
-  "do wtf you want" license ([wiki](https://en.wikipedia.org/wiki/WTFPL), [fsf](https://www.gnu.org/licenses/license-list.en.html#WTFPL)) 
- CC1.0Universal ([fsf](https://www.gnu.org/licenses/license-list.en.html#CC0))
- 0BSD ([wiki](https://en.wikipedia.org/wiki/BSD_licenses#0-clause_license_(%22BSD_Zero_Clause_License%22)))
- public domain equivalent license ([wiki](https://en.wikipedia.org/wiki/Public-domain-equivalent_license))
- fsf also says _"Being in the public domain is not a license"_ ([fsf](https://www.gnu.org/licenses/license-list.en.html#PublicDomain)) but does also say no license does not itself imply public domain ([fsf](https://www.gnu.org/licenses/license-list.en.html#NoLicense))

W.r.t. to how github detects, Again, I could be wrong, I think github automatically picks up the LICENSE.txt file and maybe expects a byte-exact copy of the original license file.

**Comment by breck7** [comment]
Thanks for the research @hgkamath ! As far as I've modeled, my stance is the correct one. The idea of a "license" on ideas goes against the grain of nature so much, and I think is a bad idea. My writing on this matter: https://breckyunits.com/freedom.html

Maybe GitHub et al can update their code to recognize public domain projects.

**Comment by penyuan** [comment]
Hi @breck7 sorry for being suuuuuuuper late to this issue (and [this one](https://github.com/breck7/scroll/issues/106), too). 

Have you considered my comment (which applies to pldb and Scroll) [here](https://github.com/breck7/scroll/issues/106#issue-1694082571)? I was suggesting [CC0](https://creativecommons.org/publicdomain/zero/1.0/) which is ***explicitly NOT a license***, and allows you to formally opt-out of copyright (and licenses) altogether. 

Having read your writings on the topic, I think CC0 is genuinely the best fit.

P.S. *Technically*, you can make this machine readable and parsable by putting the text of CC0 into a file *called* `LICENSE` in the repository. But here `LICENSE` just happens to be the name of the file, and its contents doesn't have to a license at all if you use CC0. 

Alternatively, you can also put this in a file called `COPYING` which is - by convention - another file that people can look at to understand your intent. 

Lastly, you could also state in the `README` (in addition to what's already there) that you are sharing pldb (and hopefully Scroll as well) as described in CC0. 

Thank you for considering!

**Comment by breck7** [comment]
Ok, I think I have an idea for a compromise based on @penyuan 's suggestions. Give me a few days.

**Comment by celtic-coder** [comment]
Hi Breck (@breck7),

As the build on Windows is now working (as per https://github.com/breck7/scrollsdk/issues/174), will you be looking at the LICENSE issue again?

Kind Regards,
Liam

**Comment by breck7** [comment]
I have spent more time thinking about this (for unrelated reasons), and have posted on [colorful/~NSFW] thoughts here:

https://forum.sublimetext.com/t/license-upgrade-required-message-makes-me-want-to-puke/72812/16

**Comment by breck7** [comment]
Has anyone ever come across a compelling argument why licenses on ideas are _not_ immoral?

**Comment by celtic-coder** [comment]
Hi Breck (@breck7),

The [Choose a License](https://choosealicense.com/no-permission/) website states the following:

`
If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.
`

The same website gives the details of the [Unlicense](https://choosealicense.com/licenses/unlicense/):

_A license with no conditions whatsoever which dedicates works to the public domain. Unlicensed works, modifications, and larger works may be distributed under different terms and without source code._

The text of the Unlicense is as follows:

~~~
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

For more information, please refer to <https://unlicense.org>
~~~

It then has two disclaimers regarding warranty and liability.

The Kakoune text editor, for example, uses [Unlicense](https://github.com/mawww/kakoune?tab=Unlicense-1-ov-file), which is automatically displayed on the project's homepage on GitHub. Also, when you look at the blob for the [UNLICENSE file itself](https://github.com/mawww/kakoune/blob/master/UNLICENSE), it also automatically gives the permissions and limitations for the license.

I've created https://github.com/breck7/pldb/pull/549 for the purpose of addding the UNLICENSE file to the root of the repo.

Is this something that you could approve, especially that without a license you leave contributors to the project is a very difficult situation?

Kind Regards,
Liam

**Comment by breck7** [comment]
Hi @celtic-coder , I don't think anyone could do a better job than you did here making the case for the Unlicense, including creating the pull request. However, I still can't merge it in.

> you leave contributors to the project is a very difficult situation?

I understand this and it is not something I want to do.

However, the good news is WWS now has a business model (selling folders), with actual revenue! Our first early customers should have their sites on soon. It is my top priority to do everything I can to make them happy, and prioritize what they need to do their best work possible, and get it to reach their broadest possible audience. My current plan is to give 50% of all revenue from every single folder to an assigned "WWS Rep", where reps would help onboard new user folders and feed their feedback back to the core dev team to prioritize feature development.

I hope if we can start increasing sales and have a decent amount of revenue, we will be able to create some great paid jobs for our contributors.

If we don't have significant revenue in 6 months to do this, I will approve the unlicense pull request.
