### ISSUE TITLE
File rows/slim.pldb seems to be a mixture of many things

### ISSUE THREAD

**Issue by ghost** [breck7/pldb#506]
Website - http://slim-lang.com seems to refer to website that was originally rows/slim-lang.pldb , a ruby project
documentation key seems to refer to https://www.slimframework.com/docs/v4/ , a php framework.
hacker news key is about the ruby project discussion

there are two papers linked to semantic scholar :
One seems to be a java framework/java related project.
The other seems to be about genetics, the actual paper is behind a paywall but it does not seem to mention java that much.

Should this file be deleted ?

**Comment by breck7** [comment]
Would accept a pull request to fix.
