### ISSUE TITLE
File concepts/spade.pldb seems to be mixture of too many things

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#510]
The key reference has a value poiting to an article about a hardware related langugage that has published in 2008.
it is supposed to have appeared in 2018 but links to hopl  article about a mainframe.

The only open reference to the hopl article is at http://ckw.phys.ncku.edu.tw/public/pub/Notes/Computers/Lectures/Old/Programming/The%20Language%20List%20-%20Version%202_4,%20January%2023,%201995.htm

Semantic scholar links both cite articles published well before the appeared date.

**Comment by breck7** [comment]
You are right. This looks like one of my early Google crawling scripts added it. Will remove since it's not clear which, if any, of the spades are lang worth noting here.

**Comment by SRS-WRKS** [comment]
Closed, as fixed by project owner.
