### ISSUE TITLE
add langugage spark

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#511]
appeared 1988
https://en.wikipedia.org/wiki/SPARK_(programming_language)
https://hopl.info/showlanguage.prx?exp=2518

It was earlier mixed in with Apache spark.

**Comment by breck7** [comment]
Thanks hari!

**Comment by SRS-WRKS** [comment]
@breck7 : Just to clarify, those were not instructions for others to add  a language file.
Those were Requests for comments, so that others could help in decision making :) .

Next time if you feel so, you could simple give me the go ahead to add the entry.
