### ISSUE TITLE
pldb.com site down?

### ISSUE THREAD

**Issue by FeldrinH** [breck7/pldb#515]
I tried opening https://pldb.com/ and got ERR_CONNECTION_TIMED_OUT. Is this a known problem?

**Comment by unix-junkie** [comment]
I confirm the issue. Have to use the [web archive](https://web.archive.org/web/20230613000400/https://pldb.com/) instead.

**Comment by breck7** [comment]
Hi all,

There is the static version served by GitHub here: https://pldb.pub/. Search does not currently work on that yet though. I had plans to make search isomorphic, but didn't get it done. If you need search, you can git clone the site and run it locally.

Personally I'm going through a tough time and can't afford the Digital Ocean anymore and also can't afford to keep renting PLDB.com from Venture.com.

If someone is interested in taking over PLDB.com (they charge ~$200/month) and managing the web server, I think you could maybe find a way to make a business of it better than I did. Feel free to reach out breck7@gmail.com.

I did not do a good job of managing this project and apologize for that. I still find it interesting and want to keep contributing but I'm not a good leader of it and never found a good monetization model.

Best,
Breck

**Comment by FeldrinH** [comment]
> (they charge ~$200/month)
Do you mean that Venture.com charges ~$200/month just for the domain?

**Comment by breck7** [comment]
@FeldrinH yes I own `pldb.pub` and `pldb.io` but last year thought it might be worth it to have `pldb.com`, which Venture.com was renting for $200/month, and try to turn it into a business. But then I thought PLDB as a business wouldn't really make sense. I did not want to put ads on it.

If someone wants to run `PLDB.io` and stand up a webserver running that, I am happy to transfer that domain and assist.

**Comment by ahungry** [comment]
Good aspirations :smile: (I just circled back around when trying to remember what project I saw the AWStats-like analytics on, which was this one, on the SSL connection issue ticket).

I think Venture was the big winner here - as an unregistered domain is only $5 to $15 a year (not month) from Namecheap (and hosting can be as little as $5/month for that type of traffic on a Linode, even post-acquisition) - so if you made it a year, their profit was about $2395 to do basically nothing but squat a domain and let you temporarily use it :crying_cat_face:

**Comment by breck7** [comment]
Okay all. I got my act together :).

Restored (and improved.).

Thanks everyone for your help in making this a useful project and a good example for the web.
