### ISSUE TITLE
Add Cognate

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#534]
https://cognate-lang.github.io/learn.html

Someone want to add this?

Just follow the readme, or watch a screencast on how: https://pldb.io/posts/addLanguageDemo.html

**Comment by ravixalgorithm** [comment]
I want to add, can I contribute to it??

**Comment by breck7** [comment]
@ravixalgorithm you never need to ask for permission to submit pull requests on github.

go for it!

**Comment by ravixalgorithm** [comment]
Thanks a lot, I would love to contribute
