### ISSUE TITLE
All ids to external sources should be urls (where possible)

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#54]
Right now for things like Wikipedia the grammar asks for the full url but for things like reddit it just asks for the subreddit id. For example. `subreddit Python`

The url is the clear way to go. It's a little bit of redundancy, but it makes each `pldb` file more useful on its own. And it's clearer for a new contributor what needs to be added (always just a url, never need to look up the encoding/decoding scheme).

**Comment by breck7** [comment]
Here is reddit: https://github.com/breck7/pldb/commit/e8a547b5a88cad9446a01d39578a081e9bc052bb

**Comment by breck7** [comment]
Also reddit: https://github.com/breck7/pldb/commit/5b08647c5c1c96838ac38ef2b31e7e728aad3001

**Comment by breck7** [comment]
`hoplNode` should `extend abstractUrlGuidNode`

**Comment by breck7** [comment]
`meetupNode` should probably `extend abstractUrlGuidNode`

**Comment by breck7** [comment]
`replitNode` should probably `extend abstractUrlGuidNode`

**Comment by breck7** [comment]
`rosettaCodeNode` should probably extend abstractUrlGuidNode

**Comment by breck7** [comment]
`twitterNode` should definitely `extend abstractUrlGuidNode`

**Comment by breck7** [comment]
`ubuntuPackageNode` should probably `extend abstractUrlGuidNode`

**Comment by breck7** [comment]
`tryItOnlineNode` should probably extend abstractUrlGuidNode

**Comment by breck7** [comment]
`codeMirrorNode` should probably `extend abstractUrlGuidNode`

**Comment by breck7** [comment]
`monacoNode`  should probably `extend abstractUrlGuidNode`

**Comment by SRS-WRKS** [comment]
@breck7 , I can help if someone teaches me how to write treenotation grammar :)

**Comment by breck7** [comment]
Okay let's do a live coding session soon on Twitch.

**Comment by SRS-WRKS** [comment]
Or we could do a screencast of issues like

-  https://github.com/breck7/pldb/issues/15 
- https://github.com/breck7/jtree/issues/87
-  https://devblogs.microsoft.com/oldnewthing/ 

??

Because your expectations for the screencast might not fit into my/viewers skill set ??

live coding sessions and pair programming requires being able to ask you good questions :)

**Comment by breck7** [comment]
Okay I'll do a screencast.

**Comment by breck7** [comment]
Okay part 1 of screencast:

https://www.youtube.com/watch?v=D-hn3nrLTh4

**Comment by breck7** [comment]
Part 2 of 2: https://www.youtube.com/watch?v=KQJN0xeV-1Y

**Comment by mahadwaseem123** [comment]
> `meetupNode` should probably `extend abstractUrlGuidNode`

Hi @breck7 , its done

**Comment by breck7** [comment]
This would be nice to make sure all of these are done but not urgent
