### ISSUE TITLE
Add Public release date column

### ISSUE THREAD

**Issue by ghbook** [breck7/pldb#556]
On https://pldb.io/lists/creators.html page, it would be better if we had when programming language was first released to public. So that people can sort newest and oldest languages.

**Comment by breck7** [comment]
Hi @ghbook ! You can see and sort that data on the Explorer page: https://pldb.io/lists/explorer.html

Does that solve your issue or is it something else?

**Comment by breck7** [comment]
> Is it possible to add Country of origin on creators page? 

Yes! We just started adding those:
https://github.com/breck7/pldb/blob/64ed06d4d0458afed785759c34f800f83cae192c/creators/creators.scroll#L1196

But have a lot more to add. Pull requests appreciated!
