### ISSUE TITLE
Combining `lil-pl` and `earnest-lil`

### ISSUE THREAD

**Issue by JohnEarnest** [breck7/pldb#574]
I was just doing some browsing and noticed that https://pldb.io/concepts/lil-pl.html is a duplicate of https://pldb.io/concepts/earnest-lil.html . What's the procedure for merging these? The latter (`earnest-lil`) contains the most accurate/current information.

**Comment by JohnEarnest** [comment]
Thanks, Breck!

**Comment by breck7** [comment]
Thanks @JohnEarnest ! In a minute or two https://pldb.io/concepts/lil.html should point to what used to be called earnest-lil
