### ISSUE TITLE
Add EBCDIC

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#592]
https://en.wikipedia.org/wiki/EBCDIC

**Comment by breck7** [comment]
just saw while reading https://programmingsimplicity.substack.com/p/why-do-we-use-whitespace-to-separate

**Comment by heber59** [comment]
hi, can you tell me more about the issue ?

**Comment by breck7** [comment]
@heber59 here I recorded a screencast of doing it.

https://www.youtube.com/watch?v=ytdcxNBVAX8
