### ISSUE TITLE
Cannot search for "homoiconic"

### ISSUE THREAD

**Issue by Zireael07** [breck7/pldb#598]
No results. But the site lists A LOT of Lisp variants as well as several Smalltalk variants, most of which are likely homoiconic. (Not to mention others I might not know about)

**Comment by breck7** [comment]
Ah, you are right! Sorry the search was actually a structured search and not actually doing Full Text Search like it said. That was a mistake.

I've just pushed a new search that uses some newer Scroll stuff. Now it's closer to a full text search of the entire site (the full text of all languages, features, and blog posts). It's a little slower than I'd like, and it's exact string match, but at least now it works for queries like "homoiconic": https://pldb.io/search.html#q=homoiconic

Thank you for the report @Zireael07 !
