### ISSUE TITLE
Fix Git SVG Overlap with Navigation Menu

### ISSUE THREAD

**Issue by kugurerdem** [breck7/pldb#607]
I just noticed that when the screen width decreases, the Git SVG overlaps with the navigation menu. This is bad user experience on mobile devices.

![image](https://github.com/user-attachments/assets/bf903dc3-cbe9-4c8a-8fe2-6cf9d2249677)

**Comment by kugurerdem** [comment]
Will try to fix it today, but if I don't I will tag the issue with `helpWanted` tag.

**Comment by breck7** [comment]
Fixed!

https://www.youtube.com/watch?v=NLU3xKUsnwg

Thanks @kugurerdem !!
