### ISSUE TITLE
Add "attempt this online" field?  (or repurpose tryitonline?)

### ISSUE THREAD

**Issue by bradcray** [breck7/pldb#612]
I loved tryitonline when it was being actively maintained, but nowadays use Attempt This Online exclusively, which carries on the tradition and has some nice plus-ups (like having the URL auto-update to be copy-pasteable).  This issue asks whether an attempt this online field could be added to the language profiles, or potentially if the tryitonline field could be repurposed/redefined to support either type of site?

**Comment by breck7** [comment]
moving issues to ScrollHub https://issues.pldb.io/AttemptThisOnline.html
