### ISSUE TITLE
Fill column `country`

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#62]
Currently less than <3000. This one should be a relatively easy one to 3x.

https://pldb.com/posts/originCountries.html

**Comment by breck7** [comment]
Wow, we now have this info for 3,247 langs! Great work @SRS-WRKS !!

1,519 left to go:

https://build.pldb.com/search?q=select+type+reference+website%0D%0Amissing+country

**Comment by SRS-WRKS** [comment]
@breck7 : Sorry for delay, will get back to it in the near future. 

On the bright side, i today was introduced to a new way to query treebase :)

**Comment by celtic-coder** [comment]
> Wow, we now have this info for 3,247 langs! Great work @SRS-WRKS !!

Yes, this is excellent work! 👍

**Comment by SRS-WRKS** [comment]
@celtic-coder : Thank you for the kind words. Sorry for the delay, hope to continue on this in the near future. Till we meet again in another comment thread :)

**Comment by stavares843** [comment]
i've tried

[pldb.com/search?q=select+type+reference+website%0D%0Amissing+country](https://build.pldb.com/search?q=select+type+reference+website%0D%0Amissing+country)


but redirects to https://pldb.com/languages/search.html and isn't displaying the missing entries, let me know!

**Comment by breck7** [comment]
Try search.html! Sorry I broke the link. Search is now at search.html. Things should stabilize soon! Biggest change in 5 years (static site => dynamic site)

**Comment by stavares843** [comment]
thanks 🔨

**Comment by breck7** [comment]
Thanks H for all the work on this!

I'm going to close all issues that are of type "we need more data about column X". Since I see now that this will always be the case
