### ISSUE TITLE
Fill `screenshot` keyword for all languages with `type visual`

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#63]
For visual languages, a picture is worth a thousand words. PLDB now shows a screenshot for visual languages when that keyword is present. Example: https://pldb.com/languages/scratch.html

For every visual language, let's take our own nice screenshot of using the language in action.

See the below commit which added 2 examples:
https://github.com/breck7/pldb/commit/b36729679a39c0e51253050891c6101ef753788d

### Steps:

1.  Take a screenshot of your screen using the visual language.
2. Save it in `site/screenshots/[pldbId].png`
3. Add a line to the file like this: `screenshot https://pldb.com/screenshots/explorer.png`
4. If doing this locally, run `npm run format` before committing.
5. Commit and push and send a PR

**Comment by IsSafrullah** [comment]
@breck7 for screenshots, does it have to be the application or the website page?

**Comment by breck7** [comment]
Good question @IsSafrullah! It should be a screenshot of the actual running application (so a real screenshot that you took yourself, not a screenshot from the web). There's so few visual languages that it is just much simpler and higher quality to take our own original screenshots of the actual running products than to do anything clever.

**Comment by IsSafrullah** [comment]
@breck7 got it thanks for the info

**Comment by breck7** [comment]
I'm going to close all issues that are of type "we need more data about column X". Since I see now that this will always be the case
