### ISSUE TITLE
Broken links in "Written In"

### ISSUE THREAD

**Issue by celtic-coder** [breck7/pldb#64]
Hi Breck (@breck7),

In the "Written In" section of the https://edit.pldb.com/pages/acknowledgements.html page, the individual URLs contain the **BASE_URL** replacement word, which has either not been replaced or is not required in its current form.

For example, the JavaScript link is: https://edit.pldb.com/pages/BASE_URL/languages/javascript.html

Since, I'm guessing that the URL should be either https://edit.pldb.com/languages/javascript.html or https://pldb.com/languages/javascript.html, then perhaps a replacement has already taken place?

It would appear that the **WRITTEN_IN_TABLE** is being replaced correctly, but that any internal replacements are being left "as-is". Should this replacement happening recursively or does it need to occur at another point in the processing of the page? 

Kind Regards,
Liam

**Comment by breck7** [comment]
Thanks for the very clear report @celtic-coder ! Just pushed a fix.
