### ISSUE TITLE
Make Scroll Dataset for PLDB contributors. Then acknowledgements page: everyone who has contributed code to this repo should be able to add their preferred website/email/twitter/etc if they want

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#67]

**Comment by breck7** [comment]
Ok figured this out. Will have a users database: https://github.com/breck7/pldb/commit/1a4b2f61634d30f45cb04e99b812b268f9558c85

**Comment by StuartDambi** [comment]
Hello @breck7, I would like to work on this one.

**Comment by breck7** [comment]
@codedbystuart was this you (sorry I got an email from GitHub but I don't see the comment here):

![Screen Shot 2022-09-27 at 6 56 18 AM](https://user-images.githubusercontent.com/74692/192588943-06b69aca-c2b5-4e07-a5db-939e651bdafe.png)

**Comment by StuartDambi** [comment]
Hello @breck7, yes this was me. I want to work on this issue.

**Comment by breck7** [comment]
awesome! go for it!

**Comment by breck7** [comment]
https://github.com/breck7/pldb/issues/82

**Comment by breck7** [comment]
We could make a Scroll Dataset (https://scroll.pub/blog/datasets.html) for PLDB Contributors.

**Comment by breck7** [comment]
We should do this at some point, but not urgent
