### ISSUE TITLE
influenced graph and links between languages

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#69]
should start adding more and better links on how these languages are related.

i think Diarmuid Pigott's HOPL really pioneered this. does anyone know him? he would definitely be the expert here i think.

**Comment by celtic-coder** [comment]
Hi Breck (@breck7),

Diarmuid is on [LinkedIn](https://www.linkedin.com/in/diarmuid-pigott-6a59056/), but does not appear to have any useful contact information. Is there a possibility of sending him a private message, perhaps? Or might some other contributor be able to assist with the relationships between languages?

Kind Regards,
Liam

**Comment by breck7** [comment]
Great idea @celtic-coder !

Does anyone know Diarmuid Pigott? I didn't fine HOPL until years after I started, but that gave me confidence that this would be a good idea, if someone else thought it was a good enough idea to work on it for so long.

Maybe we could ask him for a huge favor, if we would be willing to dedicate HOPL to public domain? `© Diarmuid Pigott 1995-2020. Do not copy, do not reproduce! [why?](https://hopl.info/whynocopy.html)` I'm sure we could raise money to reward him for all his efforts (IMO HE DESERVES THE TURING PRIZE!!!!)

**Comment by breck7** [comment]
https://github.com/breck7/pldb/issues/391
