### ISSUE TITLE
speed up `git pull`

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#75]
adding the branch for the github.pldb.com mirror slowed down git pull. figure that out.

(probably just change:)
`pldb/.github/workflows/buildGithubDotPldbDotCom.yaml`

**Comment by breck7** [comment]
Alright support team here's my `.git/config`. How can we make this better? No one should be pulling the `github.pldb.com` branch automatically. No one. Slow as fuck.

How do we fix?

![Screen Shot 2022-09-10 at 3 57 14 AM](https://user-images.githubusercontent.com/74692/189486686-743562f8-c049-460a-a525-da295b91b8d2.png)

**Comment by SRS-WRKS** [comment]
creating an empty git repository and checking out only the selected branches seem to be the only option. 

pldb could contain a submodule which links to the actual  github.pldb.com mirror ?

**Comment by breck7** [comment]
That's a good idea @SRS-WRKS ! I think we don't even need to make it a submodule. Instead of building a branch with a github workflow, we should just have a repo containing the built static site, and then we just update that repo. That would feed a number of birds with one seed.

**Comment by breck7** [comment]
Closing this in favor of the other one and https://github.com/breck7/pldb/issues/310
