### ISSUE TITLE
Help filling in field `originCommunity` across all languages

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#78]
https://pldb.com/lists/originCommunities.html

**Comment by SRS-WRKS** [comment]
Origin community is a best effort service when the source is academia papers. I don't have access to the archives and i rely on portal blurbs about authors, who might have moved on to newer institutions and hence might reflect their current or latest place of employment. Is that acceptable ??

**Comment by breck7** [comment]
Do your best. We'll have lots of people (and other things) validating information later.

> when the source is academia papers.

If that's the source, a good keyword to add while you're adding originCommunity is `firstAnnouncement`.

**Comment by breck7** [comment]
@SRS-WRKS ideally we add the community they were part of when the language started. But if we add the community that they were part of in the childhood years/teenage years that is fine too, if they were still working on it.

**Comment by SRS-WRKS** [comment]
Ill try my best.

**Comment by StuartDambi** [comment]
@breck7 , is this task complete? I can as well jump in and work on this.

**Comment by breck7** [comment]
Great work H!

I am trying to close all "add more data issues on X" to clean up the GitHub issues.
