### ISSUE TITLE
Fix contributors section on acknowledgements page

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#82]
When I visit: https://api.github.com/repos/breck7/pldb/contributors, it seems to be pretty unstable (some days contributors disappear).

Perhaps https://github.com/breck7/pldb/blob/13616171ee22d000bd07a85aac131ff5ce59382d/code/SiteBuilder.ts#L218 should be figuring out the contributors from the git repo, and not from that GET url.

**Comment by thevinitgupta** [comment]
I am new to this repository and would like to contribute. Could you clarify more on what the URL is?

**Comment by breck7** [comment]
Hi @thevinitgupta . I want to iterate over everyone who has contributed to the git repo and show their name, website, that sort of thing. At first I was using that link above to fetch that info from github, but for some reason now it's not as reliable, it seems to only return a portion of hte contributors. maybe you could explore. dont sweat it if you dont figure it out right away.

thank you so much for being willing to contribute!
