### ISSUE TITLE
Building pldb with cloc requires atleast 3 GB of memory

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#88]
Locally building and testing with cloc requires at least 3 GB of RAM according to informal tests. 

Should the build scripts/tests scripts be changed to warm people who want to download and build project ??

Note: Without cloc the memory requirement for building pldb seems to be quiet less. 

Related Pull request: https://github.com/breck7/pldb/pull/87

EDIT LOG: Made the text description clearer.

**Comment by breck7** [comment]
Wow, thanks for bringing this to my attention. Can someone ping the `cloc` team and get this fixed?

We could just not require it, but cloc is 16 YEARS OLD (https://pldb.com/languages/cloc.html), so there must be something stupid I did if it is taking 3GB of RAM to build.

Thank you @SRS-WRKS . Great work.

**Comment by SRS-WRKS** [comment]
Thanks for the nice compliment @breck7  . Have a nice day.

**Comment by SRS-WRKS** [comment]
Mostly handled in update e38d7a165d6d160ea8a5e05eff52d657978fffb3
