### ISSUE TITLE
Possible duplicates: database/things/accent.pldb and database/things/accent-programming-language.pldb

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#89]
Files:
database/things/accent-programming-language.pldb
and 
database/things/accent.pldb
seem to be possible duplicates 

as both list 
https://en.wikipedia.org/wiki/Rational_Synergy#History

as reference .

Possibly related Issue #78

**Comment by breck7** [comment]
Yes they look like dupes to me. someone please merge accent-programming-language.pldb into accent

**Comment by SRS-WRKS** [comment]
Resolved in commit 702fb7b613e7ced09cf30e7abdb4e20cd80afa0c

**Comment by SRS-WRKS** [comment]
Continued in https://github.com/breck7/pldb/issues/92
