### ISSUE TITLE
Steal Massimo's Idea: list of most famous bugs?

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#90]
https://twitter.com/Rainmaker1973/status/1568258255088156672

**Comment by celtic-coder** [comment]
Except we need to be careful! The famous "bug in the computer" as supposedly found by Grace Hopper is itself a [myth](https://lunduke.substack.com/p/the-story-of-the-first-computer-bug)!

We would need to ensure that there are no bugs in our bugs! 😃

**Comment by breck7** [comment]
Maybe in 2024 :)
