### ISSUE TITLE
Question: anyone know if GitHub has a URL scheme where I can generate a GET URL with params to pre-populate a pull request?

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#93]
Does that make sense? The idea is as you edit a file on build, you have the choice to save directly or go to GitHub and submit it as a PR.

![Screen Shot 2022-09-10 at 1 55 30 AM](https://user-images.githubusercontent.com/74692/189482172-9c59474f-3d4a-4733-93f2-7ea070091271.png)

**Comment by SRS-WRKS** [comment]
You were talking about parsers getting grammar validation as a feature recently.
Would you validate the files after each web edit and what if the data sources in production become divergent from one in git hub (sent via pull requests) ?

**Comment by breck7** [comment]
> You were talking about parsers getting grammar validation, as a feature recently.

Oh yeah maybe I should add that tonight.

> what if the data sources in production become divergent from one in git

Good question. Let's cross that bridge when we come to it (enough times that it becomes a problem)

**Comment by breck7** [comment]
Oh @SRS-WRKS this is a great idea!

**Comment by SRS-WRKS** [comment]
This is as far as i have gotten on this issue :
`https://github.com/breck7/pldb/compare/main%40%7B1day%7D...main`

**Comment by breck7** [comment]
This could be an item in https://github.com/breck7/pldb/issues/53

**Comment by breck7** [comment]
Eventually we should add this
