### ISSUE TITLE
Add left arrow and right arrow for previous/next to default scroll layout that functions the same way as keyboard shortcuts left and right

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#94]
See mockup, with the < and >:

![Screen Shot 2022-09-10 at 3 35 26 AM](https://user-images.githubusercontent.com/74692/189485894-51cb1aba-4215-43fd-a044-57ab6e9c4de3.png)

**Comment by zvanshi** [comment]
Hi! I wish to contribute to your project. Please guide me where can I find your website as I am new to open-source.

Thank you

**Comment by breck7** [comment]
Scroll.pub! You got this @zvanshi ! I would like if a few people tried to implement this, and then I can choose the one that fits what I was hoping for. Even if I don't pick your implementation, I'm sure it will still be fun and educational to build one!

**Comment by adriantintpilver** [comment]
Hello,

Can you see this fix? do you like me?
I see you haven't taken this change yet for the main. Could it be that you think about this in another way? Please tell me your opinion about it, so I can improve it as you see fit.

Thanks.
Regards!

**Comment by breck7** [comment]
This went live at some point with the new version of scroll.
