### ISSUE TITLE
Test somethimes pass locally but fail on github

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#97]
Sometimes the issues caught on github are genuine .

Many times it just results in multiple repeated tests and time spent on chasing causes that don't seem to affect local development setup but only fails on github build setup. 

It would be nice if the procedure that needs to be followed is given below for reference.

Thanks.

**Comment by breck7** [comment]
FLAKEY TESTS? WE DON'T HAVE FLAKEY TESTS.

I'm intrigued. My guess is it's a case sensitive file name issue. The +46 new files had some file names that need to be cleaned up. There should be no uppercase letters, and no spaces. I don't know what else is in those. We should also add a test to `pldb/code/test.ts`to make sure we don't hit this again.

**Comment by SRS-WRKS** [comment]
Duplicate of #96
